import {AllRoutes} from '../components/Router/Router.constants.ts';

export const examNamesExported: Record<number, string> = {
    1: "Examen General",
    2: "Aspectos Legales",
    3: "Comunicaciones y documentación",
    4: "Sistema SEM",
    5: "Seguridad y bienestar del personal",
    6: "Términos Médicos",
    7: "El Cuerpo Humano",
    8: "Desarrollo y esperanza de vida",
    9: "Evaluación del paciente",
    10: "Mnemotecnias",
    11: "Manejo de la Vía Aérea",
    12: "Principios de la Farmacología",
    13: "Administración de Medicamentos",
    14: "Shock",
    15: "Reanimación: Soporte Vital Básico (SVB)",
    16: "Código Mega",
    17: "Visión médica general",
    18: "Emergencias respiratorias",
    19: "Emergencias Cardiovasculares",
    20: "Emergencias Neurológicas",
    21: "Emergencias gastrointestinales y urológicas",
    22: "Emergencias endocrinas y hematológicas",
    23: "Conceptos generales de trauma",
    24: "Inmovilización",
    25: "Hemorragias",
    27: "Lesiones de cara y cuello",
    28: "Lesiones del tejido blando",
    29: "Lesiones de cabeza y columna vertebral",
    30: "Lesiones del tórax",
    31: "Lesiones Ortopédicas",
    32: "Lesiones Abdominales y genitourinarias",
    33: "Emergencias inmunológicas",
    34: "Toxicología",
    35: "Emergencias Ambientales",
    36: "Emergencias Psiquiátricas",
    37: "Emergencias Ginecológicas",
    38: "Cuidados obstétricos y neonatales",
    39: "Emergencias pediátricas",
    40: "Emergencias Geriátricas",
    41: "Pacientes con necesidades especiales",
    42: "Operaciones de transporte",
    43: "Manejo de incidentes",
    44: "Respuesta al terrorismo y manejo de desastres"
};

// Ruta del tema asociado a cada examen, para que el estudiante pueda ir a estudiarlo.
export const examRoutesExported: Record<number, string> = {
    1: AllRoutes.GENERAL,
    2: AllRoutes.LEGAL,
    3: AllRoutes.COMMUNICATIONS,
    4: AllRoutes.SEM,
    5: AllRoutes.SECURITY_OF_PERSONAL,
    6: AllRoutes.MEDIC_TERMS,
    7: AllRoutes.HUMAN_BODY,
    8: AllRoutes.LIFE_SPEC,
    9: AllRoutes.EVALUATION,
    10: AllRoutes.MNEMOTECNIAS,
    11: AllRoutes.AIRWAY_MANAGE,
    12: AllRoutes.PHARMACOLOGY,
    13: AllRoutes.MED_ADMIN,
    14: AllRoutes.SHOCK,
    15: AllRoutes.REANIMATE_SVB,
    16: AllRoutes.MEGA,
    17: AllRoutes.MEDIC_VISION,
    18: AllRoutes.AIRWAY_EMERGENCY,
    19: AllRoutes.CARDIO_EMERGENCY,
    20: AllRoutes.NEURO_EMERGENCY,
    21: AllRoutes.GASTRO_EMERGENCY,
    22: AllRoutes.ENDOCRINE_EMERGENCY,
    23: AllRoutes.TRAUMA,
    24: AllRoutes.IMMOBILIZATION,
    25: AllRoutes.BLEEDING,
    27: AllRoutes.FACE_AND_NECK,
    28: AllRoutes.SOFT_TISSUE,
    29: AllRoutes.HEAD_AND_COLUMN_INJURIES,
    30: AllRoutes.TORAX_INJURIES,
    31: AllRoutes.FEET_INJURIES,
    32: AllRoutes.ABDO_GENI_INJURIES,
    33: AllRoutes.INMUNO_EMERGENCY,
    34: AllRoutes.TOXICOLOGY,
    35: AllRoutes.AMBIENTAL_EMERGENCIES,
    36: AllRoutes.PSIQUIATRIC_EMERGENCY,
    37: AllRoutes.GINE_EMERGENCY,
    38: AllRoutes.OBSTETRIC_CARE,
    39: AllRoutes.PEDIATRIC_EMERGENCIES,
    40: AllRoutes.GERIATRIC_EMERGENCIES,
    41: AllRoutes.SPECIAL_NEEDS_PACIENT,
    42: AllRoutes.TRANSPORT_OPERATIONS,
    43: AllRoutes.INCIDENT_MANAGEMENT,
    44: AllRoutes.TERRORIST_MANAGEMENT,
};

