import { BodySystemConfig } from './AnatomiaVisual.types';

export const BODY_SYSTEMS: BodySystemConfig[] = [
    {
        id: 'cardiovascular',
        label: 'Sistema Cardiovascular',
        description: 'Corazón, arterias y venas principales',
        icon: '❤️',
        color: 'rose',
        gradientFrom: 'from-red-600',
        gradientTo: 'to-rose-700',
        points: [
            {
                id: 'cv-1',
                cx: 95,
                cy: 130,
                label: 'Corazón',
                system: 'cardiovascular',
                question: '¿En qué lado del tórax se encuentra el corazón?',
                options: ['Lado derecho', 'Centro-izquierdo', 'Completamente a la izquierda', 'Centro exacto'],
                correct: 'Centro-izquierdo',
                explanation: 'El corazón se ubica en el mediastino, ligeramente desviado a la izquierda de la línea media esternal.',
                emoji: '🫀',
            },
            {
                id: 'cv-2',
                cx: 65,
                cy: 90,
                label: 'Arteria Subclavia',
                system: 'cardiovascular',
                question: '¿Qué estructura irriga la arteria subclavia?',
                options: ['Abdomen', 'Extremidad superior', 'Extremidad inferior', 'Cerebro'],
                correct: 'Extremidad superior',
                explanation: 'La arteria subclavia irriga principalmente la extremidad superior ipsilateral y luego continúa como arteria axilar.',
                emoji: '🩸',
            },
            {
                id: 'cv-3',
                cx: 100,
                cy: 155,
                label: 'Aorta Abdominal',
                system: 'cardiovascular',
                question: '¿Cuál es la arteria más grande del cuerpo humano?',
                options: ['Arteria pulmonar', 'Arteria femoral', 'Aorta', 'Arteria carótida'],
                correct: 'Aorta',
                explanation: 'La aorta es la arteria más grande del cuerpo. Nace del ventrículo izquierdo y se divide en aorta torácica y abdominal.',
                emoji: '🩸',
            },
            {
                id: 'cv-4',
                cx: 100,
                cy: 60,
                label: 'Arteria Carótida',
                system: 'cardiovascular',
                question: '¿Qué estructura irriga principalmente la arteria carótida?',
                options: ['Corazón', 'Pulmones', 'Cerebro y cabeza', 'Abdomen'],
                correct: 'Cerebro y cabeza',
                explanation: 'Las arterias carótidas comunes ascienden por el cuello y se dividen en carótida interna (cerebro) y externa (cabeza y cuello).',
                emoji: '🩸',
            },
            {
                id: 'cv-5',
                cx: 100,
                cy: 105,
                label: 'Vena Cava Superior',
                system: 'cardiovascular',
                question: '¿Dónde desemboca la vena cava superior?',
                options: ['Ventrículo derecho', 'Aurícula derecha', 'Aurícula izquierda', 'Ventrículo izquierdo'],
                correct: 'Aurícula derecha',
                explanation: 'La vena cava superior drena la sangre desoxigenada de la parte superior del cuerpo hacia la aurícula derecha del corazón.',
                emoji: '🩸',
            },
            {
                id: 'cv-6',
                cx: 100,
                cy: 195,
                label: 'Vena Cava Inferior',
                system: 'cardiovascular',
                question: '¿Qué sangre transporta la vena cava inferior?',
                options: ['Sangre oxigenada hacia el cuerpo', 'Sangre desoxigenada al corazón', 'Sangre oxigenada al pulmón', 'Sangre de la aorta'],
                correct: 'Sangre desoxigenada al corazón',
                explanation: 'La vena cava inferior recoge la sangre desoxigenada de la mitad inferior del cuerpo y la lleva a la aurícula derecha.',
                emoji: '🩸',
            },
            {
                id: 'cv-7',
                cx: 75,
                cy: 300,
                label: 'Arteria Femoral Derecha',
                system: 'cardiovascular',
                question: '¿Dónde se palpa el pulso femoral?',
                options: ['Fosa poplítea', 'Triángulo femoral (ingle)', 'Maléolo interno', 'Cara anterior del muslo'],
                correct: 'Triángulo femoral (ingle)',
                explanation: 'El pulso femoral se palpa en el triángulo femoral, a nivel del pliegue inguinal, a mitad de camino entre la espina ilíaca anterosuperior y la sínfisis del pubis.',
                emoji: '🩸',
            },
            {
                id: 'cv-8',
                cx: 125,
                cy: 300,
                label: 'Arteria Femoral Izquierda',
                system: 'cardiovascular',
                question: '¿Qué riesgo presenta una herida penetrante en el triángulo femoral?',
                options: ['Lesión nerviosa exclusiva', 'Hemorragia masiva difícil de controlar', 'Fractura de fémur', 'Oclusión venosa'],
                correct: 'Hemorragia masiva difícil de controlar',
                explanation: 'La arteria femoral es un vaso de gran calibre. Su lesión puede provocar hemorragia masiva y exsanguinación en minutos si no se controla.',
                emoji: '🩸',
            },
            {
                id: 'cv-9',
                cx: 90,
                cy: 120,
                label: 'Arteria Pulmonar',
                system: 'cardiovascular',
                question: '¿Qué tipo de sangre transporta la arteria pulmonar?',
                options: ['Sangre oxigenada', 'Sangre desoxigenada', 'Linfa', 'Plasma únicamente'],
                correct: 'Sangre desoxigenada',
                explanation: 'La arteria pulmonar es la única arteria del cuerpo que transporta sangre desoxigenada, desde el ventrículo derecho hacia los pulmones para su oxigenación.',
                emoji: '🫀',
            },
            {
                id: 'cv-10',
                cx: 100,
                cy: 75,
                label: 'Arco Aórtico',
                system: 'cardiovascular',
                question: '¿Cuántas ramas principales emergen del arco aórtico?',
                options: ['1', '2', '3', '4'],
                correct: '3',
                explanation: 'Del arco aórtico emergen 3 ramas: el tronco braquiocefálico, la arteria carótida común izquierda y la arteria subclavia izquierda.',
                emoji: '🫀',
            },
        ],
    },
    {
        id: 'respiratory',
        label: 'Sistema Respiratorio',
        description: 'Vías aéreas y pulmones',
        icon: '🫁',
        color: 'sky',
        gradientFrom: 'from-sky-600',
        gradientTo: 'to-blue-700',
        points: [
            {
                id: 'resp-1',
                cx: 100,
                cy: 65,
                label: 'Laringe',
                system: 'respiratory',
                question: '¿Qué estructura de la laringe se usa para la cricotirotomía?',
                options: ['Cartílago tiroideo', 'Membrana cricotiroidea', 'Epiglotis', 'Cartílago aritenoides'],
                correct: 'Membrana cricotiroidea',
                explanation: 'La membrana cricotiroidea se sitúa entre el cartílago tiroides y el cricoides. Es el sitio de acceso para la cricotirotomía de emergencia.',
                emoji: '🫁',
            },
            {
                id: 'resp-2',
                cx: 100,
                cy: 80,
                label: 'Tráquea',
                system: 'respiratory',
                question: '¿Cuánto mide aproximadamente la tráquea en un adulto?',
                options: ['2-4 cm', '5-7 cm', '10-12 cm', '15-20 cm'],
                correct: '10-12 cm',
                explanation: 'La tráquea mide entre 10-12 cm de largo y 2 cm de diámetro en adultos. Se bifurca en la carina a nivel de T4-T5.',
                emoji: '🫁',
            },
            {
                id: 'resp-3',
                cx: 75,
                cy: 105,
                label: 'Bronquio Principal Derecho',
                system: 'respiratory',
                question: '¿Por qué los cuerpos extraños se alojan con más frecuencia en el bronquio derecho?',
                options: ['Es más largo', 'Es más vertical y ancho', 'Tiene más cartílagos', 'Tiene mayor presión'],
                correct: 'Es más vertical y ancho',
                explanation: 'El bronquio principal derecho es más corto, ancho y vertical que el izquierdo, lo que facilita que cuerpos extraños o la sonda endotraqueal se introduzcan en él.',
                emoji: '🫁',
            },
            {
                id: 'resp-4',
                cx: 125,
                cy: 105,
                label: 'Bronquio Principal Izquierdo',
                system: 'respiratory',
                question: '¿Cuántos lóbulos tiene el pulmón izquierdo?',
                options: ['1', '2', '3', '4'],
                correct: '2',
                explanation: 'El pulmón izquierdo tiene 2 lóbulos (superior e inferior) debido al espacio que ocupa el corazón. El pulmón derecho tiene 3 lóbulos.',
                emoji: '🫁',
            },
            {
                id: 'resp-5',
                cx: 65,
                cy: 140,
                label: 'Pulmón Derecho',
                system: 'respiratory',
                question: '¿Cuántos lóbulos tiene el pulmón derecho?',
                options: ['1', '2', '3', '4'],
                correct: '3',
                explanation: 'El pulmón derecho tiene 3 lóbulos: superior, medio e inferior. Es ligeramente más grande que el izquierdo.',
                emoji: '🫁',
            },
            {
                id: 'resp-6',
                cx: 135,
                cy: 140,
                label: 'Pulmón Izquierdo',
                system: 'respiratory',
                question: '¿Qué signo ausculatorio indica neumotórax?',
                options: ['Estertores crepitantes', 'Ausencia de murmullo vesicular', 'Roncus difusos', 'Sibilancias espiratorias'],
                correct: 'Ausencia de murmullo vesicular',
                explanation: 'En el neumotórax, la entrada de aire al espacio pleural colapsa el pulmón afectado. La auscultación revela ausencia o disminución marcada del murmullo vesicular.',
                emoji: '🫁',
            },
            {
                id: 'resp-7',
                cx: 100,
                cy: 168,
                label: 'Diafragma',
                system: 'respiratory',
                question: '¿Qué nervio inerva principalmente el diafragma?',
                options: ['Nervio vago', 'Nervio frénico', 'Nervio intercostal', 'Nervio espinal'],
                correct: 'Nervio frénico',
                explanation: 'El nervio frénico (C3-C4-C5) es el principal motor del diafragma. Una lesión medular cervical alta puede paralizarlo, causando insuficiencia respiratoria.',
                emoji: '🫁',
            },
            {
                id: 'resp-8',
                cx: 80,
                cy: 125,
                label: 'Pleura',
                system: 'respiratory',
                question: '¿Qué es el hemotórax?',
                options: ['Aire en el espacio pleural', 'Sangre en el espacio pleural', 'Pus en el espacio pleural', 'Líquido seroso en el espacio pleural'],
                correct: 'Sangre en el espacio pleural',
                explanation: 'El hemotórax es la acumulación de sangre en el espacio pleural (entre pleura visceral y parietal). Puede comprimir el pulmón y causar insuficiencia respiratoria.',
                emoji: '🫁',
            },
        ],
    },
    {
        id: 'skeletal',
        label: 'Sistema Esquelético',
        description: 'Huesos y estructuras óseas principales',
        icon: '🦴',
        color: 'amber',
        gradientFrom: 'from-amber-500',
        gradientTo: 'to-yellow-600',
        points: [
            {
                id: 'sk-1',
                cx: 100,
                cy: 20,
                label: 'Cráneo',
                system: 'skeletal',
                question: '¿Cuántos huesos forman el cráneo adulto?',
                options: ['6', '8', '10', '14'],
                correct: '8',
                explanation: 'El neurocráneo adulto está formado por 8 huesos: frontal, 2 parietales, 2 temporales, occipital, esfenoides y etmoides.',
                emoji: '💀',
            },
            {
                id: 'sk-2',
                cx: 65,
                cy: 80,
                label: 'Clavícula Derecha',
                system: 'skeletal',
                question: '¿Cuál es el hueso más frecuentemente fracturado del cuerpo?',
                options: ['Radio', 'Clavícula', 'Fémur', 'Tibia'],
                correct: 'Clavícula',
                explanation: 'La clavícula es el hueso más fracturado del cuerpo. Las fracturas ocurren típicamente en el tercio medio por caídas sobre el hombro o mano extendida.',
                emoji: '🦴',
            },
            {
                id: 'sk-3',
                cx: 100,
                cy: 115,
                label: 'Esternón',
                system: 'skeletal',
                question: '¿Qué lesión grave puede asociarse a una fractura de esternón?',
                options: ['Lesión hepática', 'Contusión miocárdica', 'Rotura esplénica', 'Fractura de clavícula'],
                correct: 'Contusión miocárdica',
                explanation: 'La fractura de esternón por mecanismo de alta energía (ej. golpe con volante) se asocia frecuentemente con contusión miocárdica y arritmias.',
                emoji: '🦴',
            },
            {
                id: 'sk-4',
                cx: 80,
                cy: 175,
                label: 'Costilla Flotante',
                system: 'skeletal',
                question: '¿Cuáles son las costillas flotantes?',
                options: ['Costillas 1-7', 'Costillas 8-10', 'Costillas 11-12', 'Costillas 1-3'],
                correct: 'Costillas 11-12',
                explanation: 'Las costillas flotantes son la 11ª y 12ª. No tienen articulación anterior con el esternón ni con otras costillas, solo articulación posterior vertebral.',
                emoji: '🦴',
            },
            {
                id: 'sk-5',
                cx: 100,
                cy: 65,
                label: 'Columna Cervical',
                system: 'skeletal',
                question: '¿Cuántas vértebras forman la columna cervical?',
                options: ['5', '7', '9', '12'],
                correct: '7',
                explanation: 'La columna cervical tiene 7 vértebras (C1-C7). C1 (atlas) y C2 (axis) son las más especializadas, permitiendo la rotación y flexión de la cabeza.',
                emoji: '🦴',
            },
            {
                id: 'sk-6',
                cx: 100,
                cy: 135,
                label: 'Columna Torácica',
                system: 'skeletal',
                question: '¿Cuántas vértebras tiene la columna torácica?',
                options: ['7', '10', '12', '5'],
                correct: '12',
                explanation: 'La columna torácica tiene 12 vértebras (T1-T12), cada una articulada con un par de costillas. Es la región más estable de la columna.',
                emoji: '🦴',
            },
            {
                id: 'sk-7',
                cx: 75,
                cy: 305,
                label: 'Fémur Derecho',
                system: 'skeletal',
                question: '¿Cuánta sangre puede perderse en una fractura de fémur?',
                options: ['100-200 ml', '300-500 ml', '1000-2000 ml', '3000-4000 ml'],
                correct: '1000-2000 ml',
                explanation: 'Una fractura de fémur puede acumular entre 1 a 2 litros de sangre en el muslo, pudiendo causar shock hipovolémico significativo.',
                emoji: '🦴',
            },
            {
                id: 'sk-8',
                cx: 73,
                cy: 370,
                label: 'Tibia Derecha',
                system: 'skeletal',
                question: '¿Por qué las fracturas de tibia tienen alto riesgo de síndrome compartimental?',
                options: ['Por su longitud', 'Por su poca cobertura muscular y fascia rígida', 'Por su proximidad al corazón', 'Por tener muchos vasos'],
                correct: 'Por su poca cobertura muscular y fascia rígida',
                explanation: 'La tibia tiene poca cobertura muscular y los compartimentos de la pierna tienen fascia poco distensible. El edema post-fractura puede elevar la presión compartimental.',
                emoji: '🦴',
            },
            {
                id: 'sk-9',
                cx: 45,
                cy: 155,
                label: 'Radio y Cúbito',
                system: 'skeletal',
                question: '¿Cuál es la fractura más común de muñeca?',
                options: ['Fractura de escafoides', 'Fractura de Colles (radio distal)', 'Fractura de cúbito', 'Fractura de carpianos'],
                correct: 'Fractura de Colles (radio distal)',
                explanation: 'La fractura de Colles (radio distal) es la fractura más frecuente del miembro superior. Ocurre por caída sobre la mano extendida en dorsiflexión.',
                emoji: '🦴',
            },
            {
                id: 'sk-10',
                cx: 100,
                cy: 255,
                label: 'Pelvis',
                system: 'skeletal',
                question: '¿Cuánta sangre puede contener el espacio retroperitoneal en fractura pélvica grave?',
                options: ['200-300 ml', '500-700 ml', 'Hasta 3-4 litros', 'Hasta 10 litros'],
                correct: 'Hasta 3-4 litros',
                explanation: 'El espacio retroperitoneal puede acumular hasta 3-4 litros de sangre en fracturas pélvicas graves tipo open book, causando shock hemorrágico severo.',
                emoji: '🦴',
            },
        ],
    },
    {
        id: 'trauma',
        label: 'Zonas de Trauma',
        description: 'Áreas críticas en trauma prehospitalario',
        icon: '🚑',
        color: 'orange',
        gradientFrom: 'from-orange-500',
        gradientTo: 'to-red-600',
        points: [
            {
                id: 'tr-1',
                cx: 100,
                cy: 25,
                label: 'Cabeza',
                system: 'trauma',
                question: '¿Qué puntuación evalúa el daño cerebral traumático?',
                options: ['Escala de AVDI', 'Escala de Glasgow', 'Escala FOUR', 'Escala de Hunt-Hess'],
                correct: 'Escala de Glasgow',
                explanation: 'La Escala de Coma de Glasgow (GCS) evalúa apertura ocular, respuesta verbal y respuesta motora. Una puntuación ≤8 define el TCE grave e indica necesidad de manejo avanzado de vía aérea.',
                emoji: '🧠',
            },
            {
                id: 'tr-2',
                cx: 100,
                cy: 58,
                label: 'Cuello',
                system: 'trauma',
                question: '¿Qué estructura del cuello es la vía aérea definitiva en trauma cuando la intubación falla?',
                options: ['Traqueotomía quirúrgica', 'Cricotirotomía (membrana cricotiroidea)', 'Punción transtraqueal', 'Mascarilla laríngea'],
                correct: 'Cricotirotomía (membrana cricotiroidea)',
                explanation: 'La cricotirotomía de emergencia a través de la membrana cricotiroidea es el acceso quirúrgico de elección cuando falla la intubación en el paciente traumatizado ("can\'t intubate, can\'t oxygenate").',
                emoji: '🔪',
            },
            {
                id: 'tr-3',
                cx: 68,
                cy: 135,
                label: 'Tórax Derecho',
                system: 'trauma',
                question: '¿Qué lesión torácica causa desvío de la tráquea al lado contrario?',
                options: ['Hemotórax masivo', 'Neumotórax a tensión', 'Tórax inestable', 'Taponamiento cardíaco'],
                correct: 'Neumotórax a tensión',
                explanation: 'El neumotórax a tensión provoca colapso pulmonar y desviación mediastínica hacia el lado opuesto, comprimiendo el corazón y grandes vasos. Es una emergencia que requiere descompresión inmediata.',
                emoji: '⚡',
            },
            {
                id: 'tr-4',
                cx: 132,
                cy: 135,
                label: 'Tórax Izquierdo',
                system: 'trauma',
                question: '¿Dónde se ausculta mejor el pulmón izquierdo?',
                options: ['Ápex pulmonar izquierdo', 'Base pulmonar izquierda', 'Región paraesternal', 'Región axilar anterior'],
                correct: 'Base pulmonar izquierda',
                explanation: 'La base pulmonar izquierda (5° espacio intercostal línea medioaxilar) es el mejor punto para auscultar el pulmón izquierdo y confirmar la correcta colocación del tubo endotraqueal.',
                emoji: '🩺',
            },
            {
                id: 'tr-5',
                cx: 100,
                cy: 185,
                label: 'Abdomen Superior',
                system: 'trauma',
                question: '¿Qué órgano sólido es el más frecuentemente lesionado en trauma abdominal cerrado?',
                options: ['Hígado', 'Bazo', 'Riñón', 'Páncreas'],
                correct: 'Bazo',
                explanation: 'El bazo es el órgano sólido más frecuentemente lesionado en trauma abdominal cerrado. Su ruptura puede causar hemorragia masiva y shock hemorrágico.',
                emoji: '🩸',
            },
            {
                id: 'tr-6',
                cx: 100,
                cy: 235,
                label: 'Abdomen Inferior',
                system: 'trauma',
                question: '¿Qué signo indica sangrado pélvico severo en trauma?',
                options: ['Signo de McBurney positivo', 'Inestabilidad pélvica a la compresión', 'Hematoma periumbilical', 'Dolor en fosa ilíaca'],
                correct: 'Inestabilidad pélvica a la compresión',
                explanation: 'La inestabilidad pélvica al realizar compresión lateral y/o anteroposterior indica fractura pélvica con riesgo de hemorragia masiva. La cincha pélvica debe aplicarse inmediatamente.',
                emoji: '⚠️',
            },
            {
                id: 'tr-7',
                cx: 75,
                cy: 310,
                label: 'Muslo Derecho',
                system: 'trauma',
                question: '¿Cuántos litros de sangre puede acumular una fractura de fémur?',
                options: ['0.5-0.5 litros', '1-2 litros', '3-4 litros', '5-6 litros'],
                correct: '1-2 litros',
                explanation: 'Una fractura de fémur puede acumular entre 1 y 2 litros de sangre en el compartimento del muslo, equivalente a un shock hemorrágico clase III. La tracción femoral ayuda a reducir este sangrado.',
                emoji: '🦴',
            },
            {
                id: 'tr-8',
                cx: 45,
                cy: 150,
                label: 'Brazo Derecho',
                system: 'trauma',
                question: '¿Qué arteria puede lesionarse en fractura de húmero distal?',
                options: ['Arteria radial', 'Arteria braquial', 'Arteria cubital', 'Arteria axilar'],
                correct: 'Arteria braquial',
                explanation: 'La arteria braquial discurre por la cara anterior del húmero. En fracturas supracondíleas del húmero distal puede quedar atrapada o seccionada, comprometiendo la perfusión distal del brazo.',
                emoji: '🦾',
            },
            {
                id: 'tr-9',
                cx: 100,
                cy: 260,
                label: 'Pelvis',
                system: 'trauma',
                question: '¿Qué tipo de fractura pélvica tiene mayor riesgo de hemorragia?',
                options: ['Fractura de acetábulo', 'Fractura en libro abierto (open book)', 'Fractura de sacro', 'Fractura de isquion'],
                correct: 'Fractura en libro abierto (open book)',
                explanation: 'La fractura en libro abierto (disruption anterior del anillo pélvico) aumenta el volumen pélvico considerablemente, permitiendo acumular grandes cantidades de sangre en el espacio retroperitoneal.',
                emoji: '⚠️',
            },
            {
                id: 'tr-10',
                cx: 72,
                cy: 390,
                label: 'Tobillo',
                system: 'trauma',
                question: '¿Qué ligamento se lesiona más frecuentemente en esguince de tobillo?',
                options: ['Ligamento deltoideo', 'Ligamento peroneoastragalino anterior (LPAA)', 'Ligamento calcaneoperoneal', 'Ligamento tibioperoneal'],
                correct: 'Ligamento peroneoastragalino anterior (LPAA)',
                explanation: 'El LPAA es el ligamento más débil del complejo lateral del tobillo y el más frecuentemente lesionado en esguinces por inversión (pie hacia adentro). Representa el 70% de los esguinces de tobillo.',
                emoji: '🦶',
            },
        ],
    },
];
