import { DifficultyConfig, Protocol } from './ProtocolOrder.types';

export const DIFFICULTY_CONFIG: Record<string, DifficultyConfig> = {
    easy: {
        label: 'Fácil',
        description: 'Protocolos básicos con pasos simples',
        timeBonus: 5,
        hintPenalty: 10,
        color: 'emerald',
        icon: '🌱',
        maxProtocols: 4,
    },
    medium: {
        label: 'Medio',
        description: 'Protocolos intermedios con más pasos',
        timeBonus: 8,
        hintPenalty: 20,
        color: 'yellow',
        icon: '⚡',
        maxProtocols: 7,
    },
    hard: {
        label: 'Difícil',
        description: 'Protocolos avanzados con pasos críticos',
        timeBonus: 12,
        hintPenalty: 30,
        color: 'orange',
        icon: '🔥',
        maxProtocols: 10,
    },
    expert: {
        label: 'Experto',
        description: 'Todos los protocolos, máxima dificultad',
        timeBonus: 15,
        hintPenalty: 40,
        color: 'red',
        icon: '💀',
        maxProtocols: 999,
    },
};

export const PROTOCOLS: Protocol[] = [
    // ─── BLS / RCP ─────────────────────────────────────────────
    {
        id: 'rcp-adulto',
        title: 'RCP en Adulto (SVB)',
        description: 'Protocolo de Reanimación Cardiopulmonar para adultos según AHA',
        category: 'bls',
        difficulty: 'easy',
        icon: '❤️',
        color: 'from-red-600 to-rose-700',
        source: 'AHA Guidelines 2020',
        tip: 'Recuerda C-A-B: Compresiones, Airway, Breathing',
        steps: [
            { id: 'rcp-1', order: 1, emoji: '👁️', text: 'Verificar seguridad de la escena', hint: 'Lo primero siempre es tu seguridad' },
            { id: 'rcp-2', order: 2, emoji: '👤', text: 'Evaluar respuesta del paciente (estimulación verbal y táctil)', hint: 'Llámalo y sacude sus hombros suavemente' },
            { id: 'rcp-3', order: 3, emoji: '📞', text: 'Activar el Sistema de Emergencias Médicas (SEM) / llamar al 911', hint: 'Si hay alguien más, delega este paso' },
            { id: 'rcp-4', order: 4, emoji: '💛', text: 'Obtener y preparar el DEA si está disponible', hint: 'El DEA es esencial para desfibrilar' },
            { id: 'rcp-5', order: 5, emoji: '🫀', text: 'Verificar pulso carotídeo (máximo 10 segundos)', hint: 'No más de 10 segundos para decidir' },
            { id: 'rcp-6', order: 6, emoji: '👐', text: 'Iniciar compresiones torácicas (100-120/min, 5-6 cm profundidad)', hint: 'Empuja fuerte y rápido, al centro del pecho' },
            { id: 'rcp-7', order: 7, emoji: '💨', text: 'Abrir vía aérea (maniobra frente-mentón)', hint: 'Inclina la cabeza, levanta el mentón' },
            { id: 'rcp-8', order: 8, emoji: '🫁', text: 'Dar 2 ventilaciones de rescate (1 segundo c/u)', hint: 'Observa que el pecho se eleve' },
            { id: 'rcp-9', order: 9, emoji: '🔄', text: 'Continuar ciclos 30:2 hasta llegada del DEA o SVCA', hint: '30 compresiones, 2 ventilaciones = 1 ciclo' },
            { id: 'rcp-10', order: 10, emoji: '⚡', text: 'Usar DEA tan pronto esté disponible y seguir indicaciones', hint: 'Analiza, despeja y descarga si indica' },
        ],
    },
    {
        id: 'desfibrilacion',
        title: 'Uso del DEA',
        description: 'Protocolo de uso del Desfibrilador Externo Automático',
        category: 'bls',
        difficulty: 'easy',
        icon: '⚡',
        color: 'from-yellow-500 to-amber-600',
        source: 'AHA Guidelines 2020',
        tip: 'Cada minuto sin desfibrilación reduce la supervivencia un 10%',
        steps: [
            { id: 'dea-1', order: 1, emoji: '🔛', text: 'Encender el DEA (botón de encendido)', hint: 'Abre la tapa o presiona el botón' },
            { id: 'dea-2', order: 2, emoji: '🩺', text: 'Colocar electrodos en posición correcta (ápex-esternón)', hint: 'Uno bajo la clavícula derecha, otro en costado izquierdo' },
            { id: 'dea-3', order: 3, emoji: '🔌', text: 'Conectar cables de los electrodos al DEA', hint: 'Escucharás un clic al conectar' },
            { id: 'dea-4', order: 4, emoji: '📊', text: 'Ordenar que nadie toque al paciente y presionar "Analizar"', hint: '¡Alejarse! El DEA no puede analizar con movimiento' },
            { id: 'dea-5', order: 5, emoji: '⚡', text: 'Si se indica descarga: despejar área y presionar botón de choque', hint: 'Avisar "¡Todos fuera!" antes de descargar' },
            { id: 'dea-6', order: 6, emoji: '🔄', text: 'Reanudar RCP inmediatamente por 2 minutos tras la descarga', hint: 'No esperes: comienza compresiones de inmediato' },
            { id: 'dea-7', order: 7, emoji: '🔁', text: 'Permitir que el DEA reanálice y repetir ciclo si es necesario', hint: 'Sigue las instrucciones del DEA' },
        ],
    },

    // ─── VÍA AÉREA ──────────────────────────────────────────────
    {
        id: 'manejo-via-aerea',
        title: 'Manejo Básico de Vía Aérea',
        description: 'Secuencia de apertura y mantenimiento de la vía aérea',
        category: 'airway',
        difficulty: 'easy',
        icon: '💨',
        color: 'from-sky-500 to-blue-600',
        source: 'PHTLS 10ª edición',
        tip: 'Sin vía aérea permeable no hay nada más que hacer',
        steps: [
            { id: 'va-1', order: 1, emoji: '🔍', text: 'Evaluar el nivel de conciencia del paciente (AVPU)', hint: 'A: Alerta, V: Voz, P: Dolor, U: No responde' },
            { id: 'va-2', order: 2, emoji: '👀', text: 'Inspeccionar la boca en busca de cuerpos extraños', hint: 'Mira, no introduzcas dedos a ciegas' },
            { id: 'va-3', order: 3, emoji: '🤚', text: 'Realizar maniobra frente-mentón (si no hay trauma)', hint: 'Inclina cabeza, levanta mentón' },
            { id: 'va-4', order: 4, emoji: '🔧', text: 'Insertar cánula orofaríngea (Guedel) si paciente está inconsciente', hint: 'Tamaño: ángulo de mandíbula al centro de boca' },
            { id: 'va-5', order: 5, emoji: '👂', text: 'Verificar permeabilidad con Ver-Oír-Sentir', hint: '10 segundos máximo para verificar respiración' },
            { id: 'va-6', order: 6, emoji: '😷', text: 'Aplicar oxígeno con mascarilla a 15 L/min', hint: 'Alta concentración en paciente crítico' },
            { id: 'va-7', order: 7, emoji: '📊', text: 'Monitorizar saturación de oxígeno (SpO2)', hint: 'Meta: SpO2 > 94%' },
        ],
    },
    {
        id: 'obstruccion-cuerpo-extrano',
        title: 'OVACE en Adulto Consciente',
        description: 'Obstrucción de Vía Aérea por Cuerpo Extraño — paciente consciente',
        category: 'airway',
        difficulty: 'easy',
        icon: '🚫',
        color: 'from-orange-500 to-red-600',
        source: 'AHA / ERC Guidelines',
        tip: 'Pregunta: "¿Se está ahogando?" — Si no puede hablar, actúa!',
        steps: [
            { id: 'ovace-1', order: 1, emoji: '🗣️', text: 'Preguntar: "¿Puede hablar/toser?" para confirmar obstrucción severa', hint: 'Si no puede toser efectivamente: actúa' },
            { id: 'ovace-2', order: 2, emoji: '📢', text: 'Avisar al paciente que intentarás desobstruir su vía aérea', hint: 'Pide permiso y prepara al paciente' },
            { id: 'ovace-3', order: 3, emoji: '🔨', text: 'Dar 5 golpes firmes interescapulares con talón de la mano', hint: 'Inclina el tronco hacia adelante para ayudar' },
            { id: 'ovace-4', order: 4, emoji: '✋', text: 'Revisar si el objeto fue expulsado tras cada golpe', hint: 'Si salió, detente y evalúa al paciente' },
            { id: 'ovace-5', order: 5, emoji: '🤜', text: 'Realizar 5 compresiones abdominales (maniobra de Heimlich)', hint: 'Puño en epigastrio, jala hacia ti y arriba' },
            { id: 'ovace-6', order: 6, emoji: '🔁', text: 'Alternar 5 golpes + 5 compresiones hasta desobstruir o pérdida de conciencia', hint: 'Sigue hasta éxito o que pierda el conocimiento' },
            { id: 'ovace-7', order: 7, emoji: '🛐', text: 'Si pierde conciencia: acostar en el piso e iniciar RCP', hint: 'En RCP, revisar la boca antes de ventilar' },
        ],
    },

    // ─── TRAUMA ─────────────────────────────────────────────────
    {
        id: 'evaluacion-primaria',
        title: 'Evaluación Primaria (ABCDE)',
        description: 'Secuencia de evaluación inicial del paciente traumatizado',
        category: 'trauma',
        difficulty: 'medium',
        icon: '🩺',
        color: 'from-violet-600 to-purple-700',
        source: 'PHTLS / ATLS',
        tip: 'ABCDE: trata primero lo que mata primero',
        steps: [
            { id: 'ep-1', order: 1, emoji: '🦺', text: 'Control de hemorragia masiva (si existe) — torniquete o compresión directa', hint: '"X" de la nemotecnia xABCDE: hemostasia primero' },
            { id: 'ep-2', order: 2, emoji: '💨', text: 'A — Vía Aérea: evaluar y asegurar con control de columna cervical', hint: 'Inmoviliza la columna si hay mecanismo de trauma' },
            { id: 'ep-3', order: 3, emoji: '🫁', text: 'B — Ventilación: frecuencia, profundidad, auscultación bilateral', hint: 'Busca neumotórax a tensión, tórax inestable' },
            { id: 'ep-4', order: 4, emoji: '❤️', text: 'C — Circulación: pulso, presión, sangrado externo, perfusión', hint: 'Control de hemorragia oculta' },
            { id: 'ep-5', order: 5, emoji: '🧠', text: 'D — Déficit neurológico: AVPU, Escala de Glasgow, pupilas', hint: 'Glasgow < 8 = vía aérea definitiva' },
            { id: 'ep-6', order: 6, emoji: '👕', text: 'E — Exposición/Entorno: desvestir al paciente, prevenir hipotermia', hint: 'Examina todo el cuerpo, cubre después' },
            { id: 'ep-7', order: 7, emoji: '📋', text: 'Documentar hallazgos y priorizar traslado (Platinum 10 minutos)', hint: 'Escena peligrosa o paciente inestable = traslado rápido' },
        ],
    },
    {
        id: 'control-hemorragia',
        title: 'Control de Hemorragia Externa',
        description: 'Protocolo para controlar sangrado externo severo',
        category: 'trauma',
        difficulty: 'medium',
        icon: '🩸',
        color: 'from-red-700 to-rose-800',
        source: 'STOP THE BLEED / PHTLS',
        tip: 'La hemorragia no controlada es la principal causa de muerte prevenible en trauma',
        steps: [
            { id: 'ch-1', order: 1, emoji: '🧤', text: 'Colocarse guantes y equipo de protección personal (EPP)', hint: 'Precauciones estándar siempre primero' },
            { id: 'ch-2', order: 2, emoji: '🔍', text: 'Identificar fuente y severidad del sangrado (arterial/venoso)', hint: 'Sangre roja brillante a chorro = arterial' },
            { id: 'ch-3', order: 3, emoji: '✋', text: 'Aplicar presión directa firme con apósito o tela limpia', hint: 'No quites el apósito si se empapa: agrega encima' },
            { id: 'ch-4', order: 4, emoji: '⏱️', text: 'Mantener presión continua por mínimo 5-10 minutos', hint: 'Sin levantar para verificar: rompe el coágulo' },
            { id: 'ch-5', order: 5, emoji: '🎯', text: 'Si extremidad: aplicar torniquete 5-8 cm proximal a la herida', hint: 'Para sangrado que no cede con presión en extremidades' },
            { id: 'ch-6', order: 6, emoji: '📝', text: 'Marcar hora de aplicación del torniquete en la piel del paciente', hint: 'Escribe la hora con marcador permanente' },
            { id: 'ch-7', order: 7, emoji: '🏥', text: 'Trasladar urgentemente y monitorizar signos vitales', hint: 'El torniquete no es para siempre: cirugía en < 6 horas' },
        ],
    },
    {
        id: 'inmovilizacion-columna',
        title: 'Inmovilización de Columna Vertebral',
        description: 'Protocolo de inmovilización espinal en trauma',
        category: 'trauma',
        difficulty: 'hard',
        icon: '🦴',
        color: 'from-slate-600 to-gray-700',
        source: 'PHTLS 10ª edición',
        tip: 'Inmoviliza TODA la columna como una unidad',
        steps: [
            { id: 'ic-1', order: 1, emoji: '🤝', text: 'Mantener estabilización manual alineada de la cabeza y cuello', hint: 'Un rescatista sostiene la cabeza mientras otro trabaja' },
            { id: 'ic-2', order: 2, emoji: '📏', text: 'Medir y colocar collarín cervical del tamaño adecuado', hint: 'Mide entre mandíbula y hombro para elegir talla' },
            { id: 'ic-3', order: 3, emoji: '🔄', text: 'Registrar evaluación neurológica antes de mover al paciente', hint: 'Documentar fuerza, sensibilidad y movimiento en extremidades' },
            { id: 'ic-4', order: 4, emoji: '🛏️', text: 'Posicionar tabla espinal larga junto al paciente', hint: 'La tabla debe estar al nivel del suelo donde está el paciente' },
            { id: 'ic-5', order: 5, emoji: '👥', text: 'Coordinar rodamiento en bloque hacia la tabla (mínimo 3 rescatistas)', hint: 'El que controla la cabeza da las órdenes de movimiento' },
            { id: 'ic-6', order: 6, emoji: '🔒', text: 'Asegurar tórax, pelvis y piernas con correas en la tabla', hint: 'Orden: tronco primero, luego cabeza' },
            { id: 'ic-7', order: 7, emoji: '🧲', text: 'Inmovilizar cabeza con bloques laterales y cinta frontal/mentoniana', hint: 'Nunca inmovilices la cabeza antes que el tronco' },
            { id: 'ic-8', order: 8, emoji: '✅', text: 'Reevaluar estado neurológico y circulación distal tras inmovilización', hint: 'Pulsos distales, llenado capilar y sensibilidad' },
        ],
    },

    // ─── CARDIOVASCULAR ─────────────────────────────────────────
    {
        id: 'sindrome-coronario',
        title: 'Síndrome Coronario Agudo (SCA)',
        description: 'Manejo prehospitalario del paciente con dolor torácico isquémico',
        category: 'cardio',
        difficulty: 'medium',
        icon: '💔',
        color: 'from-pink-600 to-rose-700',
        source: 'AHA / ACEP Guidelines',
        tip: 'El tiempo es músculo: cada minuto importa en el IAM',
        steps: [
            { id: 'sca-1', order: 1, emoji: '🛡️', text: 'Garantizar seguridad de la escena y EPP', hint: 'Siempre primero la seguridad' },
            { id: 'sca-2', order: 2, emoji: '🛋️', text: 'Posicionar al paciente en posición cómoda (semi-sentado preferiblemente)', hint: 'Reduce el trabajo cardíaco con esta posición' },
            { id: 'sca-3', order: 3, emoji: '😷', text: 'Administrar oxígeno si SpO2 < 94% (mascarilla 2-4 L/min)', hint: 'No se da O2 de rutina si saturación es normal' },
            { id: 'sca-4', order: 4, emoji: '💊', text: 'Administrar Aspirina 160-325 mg VO (si no contraindicada)', hint: 'Que el paciente mastique la aspirina para absorción rápida' },
            { id: 'sca-5', order: 5, emoji: '📈', text: 'Obtener y transmitir ECG de 12 derivaciones', hint: 'Fundamental para identificar el tipo de SCA' },
            { id: 'sca-6', order: 6, emoji: '💉', text: 'Establecer acceso venoso (al menos una vía IV)', hint: 'Para administrar medicamentos si es necesario' },
            { id: 'sca-7', order: 7, emoji: '📊', text: 'Monitorizar: FC, PA, SpO2, ECG continuo', hint: 'Vigilar arritmias y cambios hemodinámicos' },
            { id: 'sca-8', order: 8, emoji: '🏥', text: 'Trasladar urgentemente a Centro con cateterismo (sala de hemodinâmica)', hint: 'Notificar al hospital: "cath lab activation"' },
        ],
    },
    {
        id: 'anafilaxia',
        title: 'Anafilaxia',
        description: 'Protocolo de manejo de reacción alérgica severa',
        category: 'general',
        difficulty: 'medium',
        icon: '🐝',
        color: 'from-amber-500 to-yellow-600',
        source: 'WAO Guidelines / AAOS',
        tip: 'Epinefrina primero — no esperes para administrarla',
        steps: [
            { id: 'ana-1', order: 1, emoji: '🔍', text: 'Reconocer signos de anafilaxia: urticaria, angioedema, broncoespasmo, hipotensión', hint: 'Puede presentar solo algunos signos' },
            { id: 'ana-2', order: 2, emoji: '📞', text: 'Activar SEM y solicitar soporte avanzado si no se tiene', hint: 'La anafilaxia puede empeorar rápidamente' },
            { id: 'ana-3', order: 3, emoji: '💉', text: 'Administrar Epinefrina 0.3-0.5 mg IM en cara anterolateral del muslo', hint: 'Adultos: 0.3 mg; Niños: 0.01 mg/kg (máx 0.3 mg)' },
            { id: 'ana-4', order: 4, emoji: '🛋️', text: 'Posicionar al paciente: decúbito supino con piernas elevadas (si hipotensión)', hint: 'Si broncoespasmo predomina: posición semi-sentado' },
            { id: 'ana-5', order: 5, emoji: '😷', text: 'Administrar oxígeno a alta concentración (mascarilla 10-15 L/min)', hint: 'El broncoespasmo reduce la oxigenación' },
            { id: 'ana-6', order: 6, emoji: '💧', text: 'Establecer acceso IV e iniciar bolo de solución salina si hipotensión', hint: '1-2 litros de cristaloide en adultos' },
            { id: 'ana-7', order: 7, emoji: '🔄', text: 'Repetir Epinefrina en 5-15 minutos si no hay mejoría', hint: 'Hasta 3 dosis de epinefrina pueden ser necesarias' },
            { id: 'ana-8', order: 8, emoji: '🏥', text: 'Trasladar urgentemente aunque haya mejoría (riesgo de reacción bifásica)', hint: 'La reacción bifásica ocurre en 4-12 horas' },
        ],
    },

    // ─── NEUROLÓGICO ────────────────────────────────────────────
    {
        id: 'codigo-evc',
        title: 'Código EVC / ACV',
        description: 'Protocolo prehospitalario ante sospecha de evento vascular cerebral',
        category: 'neuro',
        difficulty: 'medium',
        icon: '🧠',
        color: 'from-purple-600 to-indigo-700',
        source: 'AHA Stroke Guidelines',
        tip: 'FAST: Face, Arms, Speech, Time — cada minuto = 1.9 millones de neuronas',
        steps: [
            { id: 'evc-1', order: 1, emoji: '⏱️', text: 'Documentar hora exacta de inicio de síntomas ("última vez bien")', hint: 'Esta hora determina si puede recibir trombólisis' },
            { id: 'evc-2', order: 2, emoji: '🧪', text: 'Aplicar escala FAST o Cincinnati para confirmar sospecha de ACV', hint: 'Face, Arms, Speech, Time' },
            { id: 'evc-3', order: 3, emoji: '🩸', text: 'Medir glucosa capilar para descartar hipoglucemia como causa', hint: 'Glucosa < 60 mg/dL puede simular ACV' },
            { id: 'evc-4', order: 4, emoji: '😷', text: 'Administrar O2 solo si SpO2 < 94%', hint: 'No dar O2 de rutina en ACV' },
            { id: 'evc-5', order: 5, emoji: '🛏️', text: 'Posicionar: cabecera a 0° si hipotensión, 30° si estable', hint: 'Cabecera a 30° reduce PIC' },
            { id: 'evc-6', order: 6, emoji: '💉', text: 'Establecer acceso IV (sin glucosa, usar solución salina)', hint: 'La glucosa puede empeorar el daño cerebral isquémico' },
            { id: 'evc-7', order: 7, emoji: '📊', text: 'Monitorizar FC, PA, SpO2, ECG y Glasgow seriado', hint: 'La PA se maneja con criterio específico en ACV' },
            { id: 'evc-8', order: 8, emoji: '📢', text: 'Notificar al hospital receptor con antelación: "Código EVC"', hint: 'Permite preparar equipo de trombólisis' },
            { id: 'evc-9', order: 9, emoji: '🏥', text: 'Trasladar al centro con capacidad de trombólisis / intervencionismo', hint: '"Time is brain": meta door-to-needle < 60 min' },
        ],
    },
    {
        id: 'crisis-convulsiva',
        title: 'Crisis Convulsiva',
        description: 'Manejo prehospitalario del paciente con convulsión',
        category: 'neuro',
        difficulty: 'easy',
        icon: '⚡',
        color: 'from-indigo-500 to-violet-600',
        source: 'AAOS Emergency Care',
        tip: 'No introduzcas nada en la boca durante la convulsión',
        steps: [
            { id: 'cc-1', order: 1, emoji: '🛡️', text: 'Proteger al paciente de lesiones (almohadillar entorno, alejar objetos)', hint: 'No lo sujetes con fuerza: puedes fracturarle huesos' },
            { id: 'cc-2', order: 2, emoji: '⏱️', text: 'Cronometrar la duración de la convulsión', hint: '> 5 minutos = estatus epiléptico (emergencia)' },
            { id: 'cc-3', order: 3, emoji: '🤐', text: 'NO introducir objetos en la boca ni sujetar la lengua', hint: 'Mito: no se traga la lengua' },
            { id: 'cc-4', order: 4, emoji: '🔄', text: 'Al ceder: posicionar en decúbito lateral (posición de recuperación)', hint: 'Previene broncoaspiración en fase postictal' },
            { id: 'cc-5', order: 5, emoji: '💨', text: 'Asegurar vía aérea permeable y administrar O2', hint: 'Succión si hay secreciones' },
            { id: 'cc-6', order: 6, emoji: '🩸', text: 'Medir glucosa capilar', hint: 'La hipoglucemia puede causar convulsiones' },
            { id: 'cc-7', order: 7, emoji: '📊', text: 'Evaluar nivel de conciencia (AVPU/Glasgow) y signos vitales', hint: 'La confusión postictal es normal y temporal' },
            { id: 'cc-8', order: 8, emoji: '🏥', text: 'Trasladar para evaluación médica completa', hint: 'Primera convulsión siempre requiere estudio' },
        ],
    },

    // ─── SHOCK ──────────────────────────────────────────────────
    {
        id: 'manejo-shock',
        title: 'Manejo del Shock Hipovolémico',
        description: 'Protocolo prehospitalario para shock por pérdida de volumen',
        category: 'shock',
        difficulty: 'hard',
        icon: '📉',
        color: 'from-rose-700 to-red-900',
        source: 'PHTLS / ATLS',
        tip: 'La hemorragia interna puede ser silenciosa — sospecha en todo trauma',
        steps: [
            { id: 'sh-1', order: 1, emoji: '🔍', text: 'Reconocer signos de shock: taquicardia, hipotensión, piel fría/pálida/húmeda', hint: 'El shock puede ser compensado inicialmente' },
            { id: 'sh-2', order: 2, emoji: '🩸', text: 'Controlar hemorragia externa visible de inmediato', hint: 'No hay resucitación efectiva sin hemostasia' },
            { id: 'sh-3', order: 3, emoji: '🛏️', text: 'Posicionar en decúbito supino (Trendelenburg modificado si disponible)', hint: 'Eleva piernas 15-30° para mejorar retorno venoso' },
            { id: 'sh-4', order: 4, emoji: '🌡️', text: 'Prevenir hipotermia: cubrir al paciente con mantas', hint: 'La tríada letal: hipotermia + acidosis + coagulopatía' },
            { id: 'sh-5', order: 5, emoji: '💉', text: 'Establecer 2 accesos IV de gran calibre (16 o 14 G)', hint: 'Mayor calibre = mayor flujo' },
            { id: 'sh-6', order: 6, emoji: '💧', text: 'Iniciar reposición con cristaloides calentados (Hartmann o SF 0.9%)', hint: 'Hipotensión permisiva en trauma penetrante: PA sistólica ~90 mmHg' },
            { id: 'sh-7', order: 7, emoji: '📊', text: 'Monitorizar FC, PA, SpO2, Glasgow y diuresis (si sonda)', hint: 'Diuresis > 0.5 ml/kg/h indica adecuada perfusión renal' },
            { id: 'sh-8', order: 8, emoji: '🏥', text: 'Trasladar urgentemente (platinum 10 minutos) a centro quirúrgico', hint: 'El control definitivo del sangrado interno es quirúrgico' },
        ],
    },

    // ─── PEDIÁTRICO ─────────────────────────────────────────────
    {
        id: 'rcp-pediatrico',
        title: 'RCP Pediátrico (Lactante < 1 año)',
        description: 'Soporte Vital Básico para lactantes según AHA',
        category: 'pediatric',
        difficulty: 'hard',
        icon: '👶',
        color: 'from-teal-500 to-cyan-600',
        source: 'AHA PALS Guidelines 2020',
        tip: 'En lactantes: 2 dedos en esternón, justo bajo línea intermamilar',
        steps: [
            { id: 'rcp-p-1', order: 1, emoji: '👁️', text: 'Verificar seguridad de la escena', hint: 'Tu seguridad es primero' },
            { id: 'rcp-p-2', order: 2, emoji: '👋', text: 'Estimular al lactante (palmear planta del pie, llamar)', hint: 'No sacudir al bebé: riesgo de síndrome del bebé sacudido' },
            { id: 'rcp-p-3', order: 3, emoji: '📞', text: 'Si no responde: llamar al 911 (o pedir a alguien que lo haga)', hint: 'Si estás solo: primero 2 minutos de RCP, luego llamas' },
            { id: 'rcp-p-4', order: 4, emoji: '🫀', text: 'Verificar pulso braquial (cara interna del brazo) máximo 10 seg', hint: 'En lactantes el pulso carotídeo es difícil de palpar' },
            { id: 'rcp-p-5', order: 5, emoji: '👆', text: 'Iniciar compresiones con 2 dedos (índice y medio) en esternón', hint: 'Profundidad: 4 cm, frecuencia: 100-120/min' },
            { id: 'rcp-p-6', order: 6, emoji: '💨', text: 'Abrir vía aérea en posición neutra (no hiperextender)', hint: 'La hiperextensión en lactantes puede obstruir la vía aérea' },
            { id: 'rcp-p-7', order: 7, emoji: '🫁', text: 'Dar ventilaciones de rescate boca a boca-nariz (soplo suave)', hint: 'Solo hasta que veas que el pecho sube ligeramente' },
            { id: 'rcp-p-8', order: 8, emoji: '🔄', text: 'Ciclos 30:2 (1 reanimador) o 15:2 (2 reanimadores sanitarios)', hint: '15:2 es la relación profesional en pediátrico' },
        ],
    },

    // ─── TOXICOLOGÍA ────────────────────────────────────────────
    {
        id: 'sobredosis-opiaceos',
        title: 'Sobredosis de Opiáceos / Naloxona',
        description: 'Manejo prehospitalario de sobredosis por opioides',
        category: 'toxicology',
        difficulty: 'hard',
        icon: '💊',
        color: 'from-emerald-600 to-green-700',
        source: 'SAMHSA / AAOS',
        tip: 'Tríada opioidea: miosis + depresión respiratoria + disminución de consciencia',
        steps: [
            { id: 'op-1', order: 1, emoji: '🛡️', text: 'Asegurar la escena (posible exposición a fentanilo o drogas)', hint: 'No toques jeringas ni polvos sin EPP adecuado' },
            { id: 'op-2', order: 2, emoji: '🔍', text: 'Evaluar nivel de conciencia, respiración y pupilas (tríada)', hint: 'Miosis puntiforme + bradipnea = sospecha de opioides' },
            { id: 'op-3', order: 3, emoji: '💨', text: 'Abrir vía aérea y asistir ventilación si FR < 8/min', hint: 'La principal causa de muerte es la apnea' },
            { id: 'op-4', order: 4, emoji: '😷', text: 'Administrar O2 suplementario a alta concentración', hint: 'Corrige hipoxia mientras preparas naloxona' },
            { id: 'op-5', order: 5, emoji: '💉', text: 'Administrar Naloxona 0.4-2 mg IM/IV/IN según protocolo', hint: 'Vía intranasal: 4 mg (2 mg por fosa nasal)' },
            { id: 'op-6', order: 6, emoji: '⏱️', text: 'Evaluar respuesta a los 2-3 minutos; repetir dosis si no hay mejoría', hint: 'Puede necesitarse hasta 10 mg en opioides sintéticos' },
            { id: 'op-7', order: 7, emoji: '⚠️', text: 'Vigilar síndrome de abstinencia aguda (agitación, vómitos, taquicardia)', hint: 'La naloxona puede precipitar abstinencia violenta' },
            { id: 'op-8', order: 8, emoji: '🏥', text: 'Trasladar aunque el paciente esté despierto (reaparición de sedación)', hint: 'La semivida de la naloxona es más corta que la del opioide' },
        ],
    },

    // ─── ESCENARIOS COMPLEJOS ────────────────────────────────────
    {
        id: 'triage-start',
        title: 'Triage START (Incidente de Múltiples Víctimas)',
        description: 'Clasificación rápida de víctimas en incidentes masivos',
        category: 'general',
        difficulty: 'expert',
        icon: '🚨',
        color: 'from-orange-600 to-red-700',
        source: 'START Triage System / SALT',
        tip: 'START: Simple Triage And Rapid Treatment — máximo 60 seg por víctima',
        steps: [
            { id: 'triage-1', order: 1, emoji: '📢', text: 'Dar orden de "los que pueden caminar, muévanse a un punto seguro"', hint: 'Estos son víctimas VERDES (leves) por definición' },
            { id: 'triage-2', order: 2, emoji: '💨', text: 'Evaluar respiración: ¿respira espontáneamente?', hint: 'Si no respira después de reposicionar vía aérea: NEGRO' },
            { id: 'triage-3', order: 3, emoji: '⚡', text: 'Si FR > 30 /min: clasificar como ROJO (inmediato)', hint: 'La taquipnea severa indica compromiso grave' },
            { id: 'triage-4', order: 4, emoji: '🫀', text: 'Evaluar circulación: pulso radial y llenado capilar', hint: 'Llenado > 2 seg o sin pulso radial = ROJO' },
            { id: 'triage-5', order: 5, emoji: '🧠', text: 'Evaluar estado mental: ¿obedece órdenes simples?', hint: 'No obedece = ROJO; Obedece y signos estables = AMARILLO' },
            { id: 'triage-6', order: 6, emoji: '🏷️', text: 'Colocar tarjeta de triage con color asignado en la víctima', hint: 'Tarjeta en muñeca derecha preferiblemente' },
            { id: 'triage-7', order: 7, emoji: '🗺️', text: 'Moverse a la siguiente víctima sin demorar más de 60 segundos', hint: 'NO iniciar tratamiento durante triage START' },
            { id: 'triage-8', order: 8, emoji: '📋', text: 'Reportar número de víctimas por categoría al Comandante de Incidente', hint: 'Información crítica para asignar recursos' },
        ],
    },
];

export const CATEGORIES = [
    { id: 'all', label: 'Todos', icon: '🎯', color: 'from-slate-500 to-gray-600' },
    { id: 'bls', label: 'SVB / RCP', icon: '❤️', color: 'from-red-500 to-rose-600' },
    { id: 'airway', label: 'Vía Aérea', icon: '💨', color: 'from-sky-500 to-blue-600' },
    { id: 'trauma', label: 'Trauma', icon: '🩹', color: 'from-violet-500 to-purple-600' },
    { id: 'cardio', label: 'Cardiovascular', icon: '💔', color: 'from-pink-500 to-rose-600' },
    { id: 'neuro', label: 'Neurológico', icon: '🧠', color: 'from-indigo-500 to-violet-600' },
    { id: 'shock', label: 'Shock', icon: '📉', color: 'from-rose-700 to-red-800' },
    { id: 'pediatric', label: 'Pediátrico', icon: '👶', color: 'from-teal-500 to-cyan-600' },
    { id: 'toxicology', label: 'Toxicología', icon: '☠️', color: 'from-emerald-600 to-green-700' },
    { id: 'general', label: 'General', icon: '🏥', color: 'from-amber-500 to-yellow-600' },
];
