import {
    GiRolledCloth,
    GiKnot,
    GiMountainClimbing,
    GiAnchor,
    GiCog,
    GiSuspensionBridge,
    GiCarabiner,
    GiStairsGoal,
    GiSnowflake1
} from "react-icons/gi";
import {FaShieldAlt, FaClipboardCheck, FaTools, FaUserShield, FaTasks, FaUsers} from "react-icons/fa";
import {MdSecurity, MdOutlineSystemUpdateAlt, MdOutlineAnalytics} from "react-icons/md";
import {TbFirstAidKit, TbLadder, TbAntenna} from "react-icons/tb";
import {BsSignpost2Fill} from "react-icons/bs";
import {AllRoutes} from "../../components/Router/Router.constants";

export type tRopeLesson = {
    id: string;
    number: number;
    title: string;
    icon: React.ReactNode;
    route: string;
    key: string;
    grade?: number;
};

export const ROPE_LESSONS: tRopeLesson[] = [
    {
        id: '1',
        number: 1,
        title: 'Introducción al Rescate con Cuerdas',
        icon: <GiRolledCloth className="w-12 h-12 mb-1 text-amber-500"/>,
        route: AllRoutes.ROPE_INTRODUCTION,
        key: 'introduccion',
    },
    {
        id: '2',
        number: 2,
        title: 'Seguridad',
        icon: <FaShieldAlt className="w-12 h-12 mb-1 text-amber-500"/>,
        route: AllRoutes.ROPE_SAFETY,
        key: 'seguridad',
    },
    {
        id: '3',
        number: 3,
        title: 'Normativas y Estándares',
        icon: <MdSecurity className="w-12 h-12 mb-1 text-amber-500"/>,
        route: AllRoutes.ROPE_STANDARDS,
        key: 'normativas',
    },
    {
        id: '4',
        number: 4,
        title: 'Pruebas de Equipo de Seguridad de Vida',
        icon: <FaClipboardCheck className="w-12 h-12 mb-1 text-amber-500"/>,
        route: AllRoutes.ROPE_EQUIPMENT_TESTING,
        key: 'pruebas-equipo',
    },
    {
        id: '5',
        number: 5,
        title: 'Cuerdas y Cintas de Seguridad de Vida',
        icon: <GiRolledCloth className="w-12 h-12 mb-1 text-amber-500"/>,
        route: AllRoutes.ROPE_WEBBING,
        key: 'cuerdas-cintas',
    },
    {
        id: '6',
        number: 6,
        title: 'Hardware de Rescate con Cuerdas',
        icon: <GiCog className="w-12 h-12 mb-1 text-amber-500"/>,
        route: AllRoutes.ROPE_HARDWARE,
        key: 'hardware',
    },
    {
        id: '7',
        number: 7,
        title: 'Equipo Personal',
        icon: <FaUserShield className="w-12 h-12 mb-1 text-amber-500"/>,
        route: AllRoutes.ROPE_PERSONAL_EQUIPMENT,
        key: 'equipo-personal',
    },
    {
        id: '8',
        number: 8,
        title: 'Nudos',
        icon: <GiKnot className="w-12 h-12 mb-1 text-amber-500"/>,
        route: AllRoutes.ROPE_KNOTS,
        key: 'nudos',
    },
    {
        id: '9',
        number: 9,
        title: 'Anclajes',
        icon: <GiAnchor className="w-12 h-12 mb-1 text-amber-500"/>,
        route: AllRoutes.ROPE_ANCHORS,
        key: 'anclajes',
    },
    {
        id: '10',
        number: 10,
        title: 'Sistemas de Anclaje',
        icon: <GiAnchor className="w-12 h-12 mb-1 text-amber-500"/>,
        route: AllRoutes.ROPE_ANCHOR_SYSTEMS,
        key: 'sistemas-anclaje',
    },
    {
        id: '11',
        number: 11,
        title: 'Protección de Arista',
        icon: <FaShieldAlt className="w-12 h-12 mb-1 text-amber-500"/>,
        route: AllRoutes.ROPE_EDGE_PROTECTION,
        key: 'proteccion-arista',
    },
    {
        id: '12',
        number: 12,
        title: 'Empaquetamiento del Paciente',
        icon: <TbFirstAidKit className="w-12 h-12 mb-1 text-amber-500"/>,
        route: AllRoutes.ROPE_PATIENT_PACKAGING,
        key: 'empaquetamiento-paciente',
    },
    {
        id: '13',
        number: 13,
        title: 'Camillas y Aparejo de Camillas',
        icon: <TbFirstAidKit className="w-12 h-12 mb-1 text-amber-500"/>,
        route: AllRoutes.ROPE_LITTER_RIGGING,
        key: 'camillas-aparejo',
    },
    {
        id: '14',
        number: 14,
        title: 'Sistemas de Doble Tensión',
        icon: <GiSuspensionBridge className="w-12 h-12 mb-1 text-amber-500"/>,
        route: AllRoutes.ROPE_TWIN_TENSION_SYSTEMS,
        key: 'sistemas-doble-tension',
    },
    {
        id: '15',
        number: 15,
        title: 'Sistemas de Aseguramiento (Belay)',
        icon: <GiCarabiner className="w-12 h-12 mb-1 text-amber-500"/>,
        route: AllRoutes.ROPE_BELAY_SYSTEMS,
        key: 'sistemas-aseguramiento',
    },
    {
        id: '16',
        number: 16,
        title: 'Sistemas de Descenso',
        icon: <MdOutlineSystemUpdateAlt className="w-12 h-12 mb-1 text-amber-500"/>,
        route: AllRoutes.ROPE_LOWERING_SYSTEMS,
        key: 'sistemas-descenso',
    },
    {
        id: '17',
        number: 17,
        title: 'Sistemas de Izado y Ventaja Mecánica',
        icon: <GiCog className="w-12 h-12 mb-1 text-amber-500"/>,
        route: AllRoutes.ROPE_RAISING_SYSTEMS,
        key: 'sistemas-izado',
    },
    {
        id: '18',
        number: 18,
        title: 'Reversión de un Sistema',
        icon: <MdOutlineSystemUpdateAlt className="w-12 h-12 mb-1 text-amber-500"/>,
        route: AllRoutes.ROPE_REVERSING_SYSTEM,
        key: 'reversion-sistema',
    },
    {
        id: '19',
        number: 19,
        title: 'Paso de Nudo en un Sistema',
        icon: <GiKnot className="w-12 h-12 mb-1 text-amber-500"/>,
        route: AllRoutes.ROPE_KNOT_PASS,
        key: 'paso-de-nudo',
    },
    {
        id: '20',
        number: 20,
        title: 'Análisis de un Sistema de Rescate',
        icon: <MdOutlineAnalytics className="w-12 h-12 mb-1 text-amber-500"/>,
        route: AllRoutes.ROPE_ANALYZING_SYSTEM,
        key: 'analisis-sistema',
    },
    {
        id: '21',
        number: 21,
        title: 'Rapel',
        icon: <GiMountainClimbing className="w-12 h-12 mb-1 text-amber-500"/>,
        route: AllRoutes.ROPE_RAPPELLING,
        key: 'rapel',
    },
    {
        id: '22',
        number: 22,
        title: 'Ascenso',
        icon: <GiMountainClimbing className="w-12 h-12 mb-1 text-amber-500"/>,
        route: AllRoutes.ROPE_ASCENDING,
        key: 'ascenso',
    },
    {
        id: '23',
        number: 23,
        title: 'Protección Contra Caídas',
        icon: <FaShieldAlt className="w-12 h-12 mb-1 text-amber-500"/>,
        route: AllRoutes.ROPE_FALL_PROTECTION,
        key: 'proteccion-caidas',
    },
    {
        id: '24',
        number: 24,
        title: 'Acceso y Estabilización',
        icon: <FaTools className="w-12 h-12 mb-1 text-amber-500"/>,
        route: AllRoutes.ROPE_ACCESS_STABILIZATION,
        key: 'acceso-estabilizacion',
    },
    {
        id: '25',
        number: 25,
        title: 'Recogida Estándar de Persona (Pick-Off)',
        icon: <FaUsers className="w-12 h-12 mb-1 text-amber-500"/>,
        route: AllRoutes.ROPE_PERSON_PICK_OFF,
        key: 'recogida-persona',
    },
    {
        id: '26',
        number: 26,
        title: 'Evacuaciones en Alto Ángulo',
        icon: <GiMountainClimbing className="w-12 h-12 mb-1 text-amber-500"/>,
        route: AllRoutes.ROPE_HIGH_ANGLE_EVACUATIONS,
        key: 'evacuacion-alto-angulo',
    },
    {
        id: '27',
        number: 27,
        title: 'Evacuaciones en Bajo Ángulo',
        icon: <TbFirstAidKit className="w-12 h-12 mb-1 text-amber-500"/>,
        route: AllRoutes.ROPE_LOW_ANGLE_EVACUATIONS,
        key: 'evacuacion-bajo-angulo',
    },
    {
        id: '28',
        number: 28,
        title: 'Líneas Guía',
        icon: <BsSignpost2Fill className="w-12 h-12 mb-1 text-amber-500"/>,
        route: AllRoutes.ROPE_GUIDING_LINES,
        key: 'lineas-guia',
    },
    {
        id: '29',
        number: 29,
        title: 'Líneas Altas (Highlines)',
        icon: <GiSuspensionBridge className="w-12 h-12 mb-1 text-amber-500"/>,
        route: AllRoutes.ROPE_HIGH_LINES,
        key: 'lineas-altas',
    },
    {
        id: '30',
        number: 30,
        title: 'Anclajes Altos y Direccionales',
        icon: <GiAnchor className="w-12 h-12 mb-1 text-amber-500"/>,
        route: AllRoutes.ROPE_HIGH_ANCHORS_DIRECTIONALS,
        key: 'anclajes-altos-direccionales',
    },
    {
        id: '31',
        number: 31,
        title: 'Sistemas de Rescate con Escaleras',
        icon: <TbLadder className="w-12 h-12 mb-1 text-amber-500"/>,
        route: AllRoutes.ROPE_LADDER_RESCUE_SYSTEMS,
        key: 'rescate-escaleras',
    },
    {
        id: '32',
        number: 32,
        title: 'Organización y Planificación',
        icon: <FaTasks className="w-12 h-12 mb-1 text-amber-500"/>,
        route: AllRoutes.ROPE_ORGANIZATION_PLANNING,
        key: 'organizacion-planificacion',
    },
    {
        id: '33',
        number: 33,
        title: 'Integración Final',
        icon: <GiStairsGoal className="w-12 h-12 mb-1 text-amber-500"/>,
        route: AllRoutes.ROPE_PUTTING_IT_TOGETHER,
        key: 'integracion-final',
    },
    {
        id: '34',
        number: 34,
        title: 'Acceso por Cuerda',
        icon: <GiCarabiner className="w-12 h-12 mb-1 text-amber-500"/>,
        route: AllRoutes.ROPE_ROPE_ACCESS,
        key: 'acceso-por-cuerda',
    },
    {
        id: '35',
        number: 35,
        title: 'Rescate en Torres de Antena y Escaleras Enjauladas',
        icon: <TbAntenna className="w-12 h-12 mb-1 text-amber-500"/>,
        route: AllRoutes.ROPE_ANTENNA_TOWER_RESCUE,
        key: 'rescate-torres-antena',
    },
    {
        id: '36',
        number: 36,
        title: 'Escape y Evacuación de Emergencia',
        icon: <FaShieldAlt className="w-12 h-12 mb-1 text-amber-500"/>,
        route: AllRoutes.ROPE_ESCAPE_BAILOUT,
        key: 'escape-evacuacion-emergencia',
    },
    {
        id: '37',
        number: 37,
        title: 'Evacuaciones en Nieve y Pendientes',
        icon: <GiSnowflake1 className="w-12 h-12 mb-1 text-amber-500"/>,
        route: AllRoutes.ROPE_SNOW_SLOPE_EVACUATIONS,
        key: 'evacuacion-nieve-pendiente',
    },
];
