import { BuzzerQuestion } from './BuzzerBattle.types';

export const TEAM_COLORS = [
    '#ef4444', // Rojo
    '#3b82f6', // Azul
    '#10b981', // Verde
    '#f59e0b', // Amarillo
    '#8b5cf6', // Púrpura
    '#ec4899', // Rosa
];

export const DIFFICULTY_POINTS = {
    'Fácil': 100,
    'Media': 200,
    'Difícil': 300,
};

export const BUZZER_QUESTIONS: BuzzerQuestion[] = [
    // === PREGUNTAS FÁCILES ===
    {
        id: 'buzz-easy-1',
        category: 'Signos Vitales',
        difficulty: 'Fácil',
        question: '¿Cuál es el rango normal de frecuencia respiratoria en un adulto?',
        answer: '12-20 respiraciones por minuto',
        options: ['8-12 rpm', '12-20 rpm', '20-30 rpm', '30-40 rpm'],
        explanation: 'La frecuencia respiratoria normal en adultos es de 12-20 respiraciones por minuto.',
        points: 100,
    },
    {
        id: 'buzz-easy-2',
        category: 'Anatomía Básica',
        difficulty: 'Fácil',
        question: '¿Qué órgano bombea la sangre a todo el cuerpo?',
        answer: 'El corazón',
        options: ['El corazón', 'Los pulmones', 'El hígado', 'Los riñones'],
        explanation: 'El corazón es el órgano muscular que bombea sangre oxigenada a todo el cuerpo.',
        points: 100,
    },
    {
        id: 'buzz-easy-3',
        category: 'RCP Básico',
        difficulty: 'Fácil',
        question: '¿Cuál es el número de emergencia en Puerto Rico?',
        answer: '9-1-1',
        options: ['9-1-1', '0-6-6', '1-1-2', '0-8-0'],
        explanation: 'El 9-1-1 es el número de emergencias en Puerto Rico y Estados Unidos.',
        points: 100,
    },
    {
        id: 'buzz-easy-4',
        category: 'Primeros Auxilios',
        difficulty: 'Fácil',
        question: '¿Qué significa la "C" en ABC de primeros auxilios?',
        answer: 'Circulación',
        options: ['Consciencia', 'Circulación', 'Compresiones', 'Control'],
        explanation: 'En el ABC de primeros auxilios, C representa Circulación.',
        points: 100,
    },
    {
        id: 'buzz-easy-5',
        category: 'Signos Vitales',
        difficulty: 'Fácil',
        question: '¿Cuál es la temperatura corporal normal en grados Celsius?',
        answer: '37°C',
        options: ['35°C', '36°C', '37°C', '38°C'],
        explanation: 'La temperatura corporal normal es aproximadamente 37°C (98.6°F).',
        points: 100,
    },
    {
        id: 'buzz-easy-6',
        category: 'Equipamiento',
        difficulty: 'Fácil',
        question: '¿Qué equipo de protección personal (EPP) es esencial para protegerse de fluidos corporales?',
        answer: 'Guantes',
        options: ['Casco', 'Guantes', 'Botas', 'Chaleco'],
        explanation: 'Los guantes son el EPP básico para protegerse del contacto con fluidos corporales.',
        points: 100,
    },
    {
        id: 'buzz-easy-7',
        category: 'Vía Aérea',
        difficulty: 'Fácil',
        question: '¿Qué maniobra se utiliza para abrir la vía aérea en un paciente sin trauma?',
        answer: 'Inclinación de cabeza y elevación del mentón',
        options: ['Tracción mandibular', 'Inclinación de cabeza y elevación del mentón', 'Compresión cricoidea', 'Elevación de hombros'],
        explanation: 'La maniobra de inclinación de cabeza y elevación del mentón es la técnica estándar para abrir la vía aérea en pacientes sin sospecha de trauma cervical.',
        points: 100,
    },
    {
        id: 'buzz-easy-8',
        category: 'Posiciones',
        difficulty: 'Fácil',
        question: '¿En qué posición se debe colocar a una persona inconsciente que respira?',
        answer: 'Posición de recuperación (lateral)',
        options: ['Boca arriba', 'Boca abajo', 'Posición de recuperación (lateral)', 'Sentado'],
        explanation: 'La posición de recuperación o lateral ayuda a mantener la vía aérea abierta y permite que los fluidos drenen.',
        points: 100,
    },
    {
        id: 'buzz-easy-9',
        category: 'Hemorragias',
        difficulty: 'Fácil',
        question: '¿Cuál es la primera acción para controlar una hemorragia externa?',
        answer: 'Presión directa',
        options: ['Torniquete', 'Presión directa', 'Elevar la extremidad', 'Aplicar hielo'],
        explanation: 'La presión directa sobre la herida es el primer método para controlar una hemorragia externa.',
        points: 100,
    },
    {
        id: 'buzz-easy-10',
        category: 'Quemaduras',
        difficulty: 'Fácil',
        question: '¿Qué tipo de quemadura afecta solo la capa superficial de la piel?',
        answer: 'Primer grado',
        options: ['Primer grado', 'Segundo grado', 'Tercer grado', 'Cuarto grado'],
        explanation: 'Las quemaduras de primer grado afectan solo la epidermis (capa superficial).',
        points: 100,
    },

    // === PREGUNTAS MEDIAS ===
    {
        id: 'buzz-med-1',
        category: 'Farmacología',
        difficulty: 'Media',
        question: '¿Cuál es el medicamento de primera línea para un paro cardíaco?',
        answer: 'Epinefrina',
        options: ['Atropina', 'Epinefrina', 'Amiodarona', 'Lidocaína'],
        explanation: 'La epinefrina (adrenalina) es el medicamento de primera línea en el manejo de paro cardíaco.',
        points: 200,
    },
    {
        id: 'buzz-med-2',
        category: 'Electrocardiografía',
        difficulty: 'Media',
        question: '¿Qué ritmo cardíaco es desfibrilable?',
        answer: 'Fibrilación ventricular',
        options: ['Asistolia', 'Fibrilación ventricular', 'Actividad eléctrica sin pulso', 'Bradicardia sinusal'],
        explanation: 'La fibrilación ventricular y la taquicardia ventricular sin pulso son ritmos desfibrilables.',
        points: 200,
    },
    {
        id: 'buzz-med-3',
        category: 'Trauma',
        difficulty: 'Media',
        question: '¿Cuál es la presión arterial sistólica mínima objetivo en un paciente con trauma penetrante?',
        answer: '90 mmHg',
        options: ['70 mmHg', '80 mmHg', '90 mmHg', '100 mmHg'],
        explanation: 'En trauma penetrante, se busca mantener una presión arterial sistólica de al menos 90 mmHg (hipotensión permisiva).',
        points: 200,
    },
    {
        id: 'buzz-med-4',
        category: 'Neurología',
        difficulty: 'Media',
        question: '¿Qué significa un puntaje de 8 o menos en la Escala de Coma de Glasgow?',
        answer: 'Coma severo/Protección de vía aérea necesaria',
        options: ['Alerta', 'Confusión moderada', 'Coma severo/Protección de vía aérea necesaria', 'Estado vegetativo'],
        explanation: 'Un GCS de 8 o menos indica coma severo y requiere protección definitiva de la vía aérea.',
        points: 200,
    },
    {
        id: 'buzz-med-5',
        category: 'Respiratorio',
        difficulty: 'Media',
        question: '¿Qué condición se caracteriza por entrada de aire en el espacio pleural?',
        answer: 'Neumotórax',
        options: ['Hemotórax', 'Neumotórax', 'Atelectasia', 'Edema pulmonar'],
        explanation: 'El neumotórax es la presencia de aire en el espacio pleural que causa colapso pulmonar.',
        points: 200,
    },
    {
        id: 'buzz-med-6',
        category: 'Pediátrico',
        difficulty: 'Media',
        question: '¿A qué edad se considera a un paciente como pediátrico en medicina de emergencia?',
        answer: 'Desde el nacimiento hasta los 18 años',
        options: ['Hasta los 12 años', 'Hasta los 14 años', 'Desde el nacimiento hasta los 18 años', 'Hasta los 21 años'],
        explanation: 'En medicina de emergencia, los pacientes pediátricos son aquellos desde el nacimiento hasta los 18 años.',
        points: 200,
    },
    {
        id: 'buzz-med-7',
        category: 'Shock',
        difficulty: 'Media',
        question: '¿Cuál es el tipo de shock causado por pérdida severa de volumen sanguíneo?',
        answer: 'Shock hipovolémico',
        options: ['Shock cardiogénico', 'Shock séptico', 'Shock hipovolémico', 'Shock neurogénico'],
        explanation: 'El shock hipovolémico es causado por pérdida significativa de volumen sanguíneo.',
        points: 200,
    },
    {
        id: 'buzz-med-8',
        category: 'Diabetes',
        difficulty: 'Media',
        question: '¿Qué nivel de glucosa en sangre se considera hipoglucemia?',
        answer: 'Menos de 70 mg/dL',
        options: ['Menos de 50 mg/dL', 'Menos de 70 mg/dL', 'Menos de 90 mg/dL', 'Menos de 110 mg/dL'],
        explanation: 'La hipoglucemia se define como glucosa en sangre menor de 70 mg/dL.',
        points: 200,
    },
    {
        id: 'buzz-med-9',
        category: 'Intoxicaciones',
        difficulty: 'Media',
        question: '¿Cuál es el antídoto específico para la sobredosis de opioides?',
        answer: 'Naloxona (Narcan)',
        options: ['Flumazenil', 'Naloxona (Narcan)', 'Atropina', 'Glucagón'],
        explanation: 'La naloxona (Narcan) es el antagonista específico de los opioides.',
        points: 200,
    },
    {
        id: 'buzz-med-10',
        category: 'Obstetricia',
        difficulty: 'Media',
        question: '¿Cuándo se considera que un parto es prematuro?',
        answer: 'Antes de las 37 semanas de gestación',
        options: ['Antes de las 35 semanas', 'Antes de las 37 semanas', 'Antes de las 39 semanas', 'Antes de las 40 semanas'],
        explanation: 'Un parto es considerado prematuro cuando ocurre antes de las 37 semanas completas de gestación.',
        points: 200,
    },

    // === PREGUNTAS DIFÍCILES ===
    {
        id: 'buzz-hard-1',
        category: 'ACLS Avanzado',
        difficulty: 'Difícil',
        question: '¿Cuál es la dosis de epinefrina en un paro cardíaco adulto?',
        answer: '1 mg IV/IO cada 3-5 minutos',
        options: ['0.5 mg IV cada 3-5 min', '1 mg IV/IO cada 3-5 min', '2 mg IV cada 5 min', '0.3 mg IM cada 3 min'],
        explanation: 'La dosis estándar de epinefrina en paro cardíaco es 1 mg IV/IO cada 3-5 minutos.',
        points: 300,
    },
    {
        id: 'buzz-hard-2',
        category: 'Farmacología Avanzada',
        difficulty: 'Difícil',
        question: '¿Cuál es el mecanismo de acción de la Amiodarona?',
        answer: 'Bloquea canales de potasio, sodio y calcio',
        options: ['Bloqueador beta selectivo', 'Bloquea canales de potasio, sodio y calcio', 'Antagonista de calcio puro', 'Agonista adrenérgico'],
        explanation: 'La Amiodarona es un antiarrítmico clase III que bloquea múltiples canales iónicos.',
        points: 300,
    },
    {
        id: 'buzz-hard-3',
        category: 'Trauma Complejo',
        difficulty: 'Difícil',
        question: '¿Qué fractura pélvica tiene mayor riesgo de hemorragia masiva?',
        answer: 'Fractura de libro abierto (tipo B)',
        options: ['Fractura por compresión lateral', 'Fractura de libro abierto (tipo B)', 'Fractura vertical', 'Fractura de rama púbica'],
        explanation: 'Las fracturas de libro abierto pueden causar hemorragia masiva del plexo venoso pélvico.',
        points: 300,
    },
    {
        id: 'buzz-hard-4',
        category: 'Neurología Crítica',
        difficulty: 'Difícil',
        question: '¿Cuál es la Triada de Cushing?',
        answer: 'Hipertensión, bradicardia y respiraciones irregulares',
        options: ['Hipotensión, taquicardia y taquipnea', 'Hipertensión, bradicardia y respiraciones irregulares', 'Fiebre, rigidez nucal y fotofobia', 'Dolor, palidez y ausencia de pulsos'],
        explanation: 'La Triada de Cushing indica hipertensión intracraneal severa.',
        points: 300,
    },
    {
        id: 'buzz-hard-5',
        category: 'Toxicología',
        difficulty: 'Difícil',
        question: '¿Qué compuesto contiene el síndrome tóxico por organofosforados?',
        answer: 'Inhibición de la acetilcolinesterasa',
        options: ['Bloqueo de receptores NMDA', 'Inhibición de la acetilcolinesterasa', 'Estimulación de receptores opioides', 'Antagonismo GABAérgico'],
        explanation: 'Los organofosforados inhiben la acetilcolinesterasa causando acumulación de acetilcolina.',
        points: 300,
    },
    {
        id: 'buzz-hard-6',
        category: 'Cardiología',
        difficulty: 'Difícil',
        question: '¿Qué segmento del ECG representa la repolarización ventricular?',
        answer: 'Onda T',
        options: ['Onda P', 'Complejo QRS', 'Onda T', 'Segmento PR'],
        explanation: 'La onda T representa la repolarización ventricular en el electrocardiograma.',
        points: 300,
    },
    {
        id: 'buzz-hard-7',
        category: 'Fisiología Avanzada',
        difficulty: 'Difícil',
        question: '¿Cuál es el volumen tidal normal en un adulto?',
        answer: '500 mL (6-8 mL/kg)',
        options: ['300 mL', '500 mL (6-8 mL/kg)', '800 mL', '1000 mL'],
        explanation: 'El volumen tidal normal es aproximadamente 500 mL o 6-8 mL por kilogramo de peso corporal.',
        points: 300,
    },
    {
        id: 'buzz-hard-8',
        category: 'Síndrome Coronario',
        difficulty: 'Difícil',
        question: '¿Qué derivaciones del ECG de 12 derivaciones muestran un infarto de pared inferior?',
        answer: 'II, III y aVF',
        options: ['V1, V2, V3', 'II, III y aVF', 'I, aVL, V5, V6', 'V3, V4'],
        explanation: 'Las derivaciones II, III y aVF muestran cambios en infartos de la pared inferior del corazón.',
        points: 300,
    },
    {
        id: 'buzz-hard-9',
        category: 'Ventilación',
        difficulty: 'Difícil',
        question: '¿Cuál es la presión de CO2 arterial normal (PaCO2)?',
        answer: '35-45 mmHg',
        options: ['25-35 mmHg', '35-45 mmHg', '45-55 mmHg', '55-65 mmHg'],
        explanation: 'La presión parcial de CO2 arterial normal es de 35-45 mmHg.',
        points: 300,
    },
    {
        id: 'buzz-hard-10',
        category: 'Sepsis',
        difficulty: 'Difícil',
        question: '¿Qué criterio define la sepsis según el consenso Sepsis-3?',
        answer: 'SOFA score ≥2 puntos',
        options: ['SIRS ≥2 criterios', 'SOFA score ≥2 puntos', 'qSOFA ≥3 puntos', 'Lactato >4 mmol/L'],
        explanation: 'Sepsis-3 define sepsis como infección con disfunción orgánica (incremento en SOFA ≥2).',
        points: 300,
    },

    // === PREGUNTAS ADICIONALES FÁCILES ===
    {
        id: 'buzz-easy-11',
        category: 'Inmovilización',
        difficulty: 'Fácil',
        question: '¿Qué dispositivo se usa para inmovilizar la columna cervical?',
        answer: 'Collar cervical',
        options: ['Férula rígida', 'Collar cervical', 'Tablilla SAM', 'Vendaje elástico'],
        explanation: 'El collar cervical se utiliza para inmovilizar la columna cervical en sospecha de trauma.',
        points: 100,
    },
    {
        id: 'buzz-easy-12',
        category: 'Valoración',
        difficulty: 'Fácil',
        question: '¿Qué evalúa el AVDI?',
        answer: 'Nivel de consciencia',
        options: ['Signos vitales', 'Nivel de consciencia', 'Dolor', 'Respiración'],
        explanation: 'AVDI evalúa el nivel de consciencia: Alerta, Verbal, Dolor, Inconsciente.',
        points: 100,
    },

    // === PREGUNTAS ADICIONALES MEDIAS ===
    {
        id: 'buzz-med-11',
        category: 'Vía Aérea Avanzada',
        difficulty: 'Media',
        question: '¿Cuál es la longitud promedio de inserción de un tubo endotraqueal en un adulto (en la comisura labial)?',
        answer: '21-23 cm en hombres, 19-21 cm en mujeres',
        options: ['15-17 cm', '17-19 cm', '21-23 cm en hombres, 19-21 cm en mujeres', '25-27 cm'],
        explanation: 'La profundidad promedio de inserción del tubo endotraqueal es 21-23 cm en hombres y 19-21 cm en mujeres.',
        points: 200,
    },
    {
        id: 'buzz-med-12',
        category: 'Convulsiones',
        difficulty: 'Media',
        question: '¿Cuál es el medicamento de primera línea para el estado epiléptico?',
        answer: 'Benzodiazepinas (Diazepam o Lorazepam)',
        options: ['Fenitoína', 'Benzodiazepinas (Diazepam o Lorazepam)', 'Fenobarbital', 'Valproato'],
        explanation: 'Las benzodiazepinas (especialmente lorazepam o diazepam) son la primera línea para el estado epiléptico.',
        points: 200,
    },

    // === PREGUNTAS ADICIONALES DIFÍCILES ===
    {
        id: 'buzz-hard-11',
        category: 'Síndrome Metabólico',
        difficulty: 'Difícil',
        question: '¿Qué valor de pH indica acidosis metabólica severa?',
        answer: 'pH < 7.20',
        options: ['pH < 7.45', 'pH < 7.35', 'pH < 7.20', 'pH < 7.00'],
        explanation: 'Un pH menor a 7.20 indica acidosis metabólica severa que requiere intervención agresiva.',
        points: 300,
    },
    {
        id: 'buzz-hard-12',
        category: 'Reanimación Pediátrica',
        difficulty: 'Difícil',
        question: '¿Cuál es la dosis de epinefrina en paro cardíaco pediátrico?',
        answer: '0.01 mg/kg IV/IO (1:10,000)',
        options: ['0.001 mg/kg', '0.01 mg/kg IV/IO (1:10,000)', '0.1 mg/kg', '1 mg total'],
        explanation: 'La dosis de epinefrina en paro pediátrico es 0.01 mg/kg de solución 1:10,000.',
        points: 300,
    },
];

export const DEFAULT_GAME_CONFIG = {
    numberOfTeams: 2,
    questionsPerRound: 10,
    timeLimit: 30,
};

