import { Flashcard } from './Flashcards.types';

export const FLASHCARDS: Flashcard[] = [
  // ─── SIGNOS VITALES (10) ───────────────────────────────────────────────────
  {
    id: 'sv-1',
    front: 'Frecuencia cardíaca normal en adulto',
    back: '60–100 latidos por minuto (lpm)',
    hint: 'Menor de 60 = bradicardia | Mayor de 100 = taquicardia',
    category: 'signos-vitales',
    difficulty: 'easy',
    emoji: '❤️',
  },
  {
    id: 'sv-2',
    front: 'Frecuencia respiratoria normal en adulto',
    back: '12–20 respiraciones por minuto (rpm)',
    hint: 'Menor de 12 = bradipnea | Mayor de 20 = taquipnea',
    category: 'signos-vitales',
    difficulty: 'easy',
    emoji: '🫁',
  },
  {
    id: 'sv-3',
    front: 'Presión arterial normal en adulto',
    back: '120/80 mmHg (sistólica/diastólica)',
    hint: 'Sistólica ≥ 140 o diastólica ≥ 90 = hipertensión',
    category: 'signos-vitales',
    difficulty: 'easy',
    emoji: '🩺',
  },
  {
    id: 'sv-4',
    front: 'Temperatura corporal normal',
    back: '36.5–37.5 °C (97.7–99.5 °F)',
    hint: '> 38 °C = fiebre | < 36 °C = hipotermia',
    category: 'signos-vitales',
    difficulty: 'easy',
    emoji: '🌡️',
  },
  {
    id: 'sv-5',
    front: 'Saturación de oxígeno normal (SpO₂)',
    back: '≥ 95% en aire ambiente',
    hint: '< 94% requiere oxígeno suplementario | < 90% = emergencia',
    category: 'signos-vitales',
    difficulty: 'easy',
    emoji: '💨',
  },
  {
    id: 'sv-6',
    front: '¿Qué es la presión de pulso?',
    back: 'Diferencia entre presión sistólica y diastólica (normal: 40–60 mmHg)',
    hint: 'PP estrecha (< 25 mmHg) puede indicar taponamiento o shock',
    category: 'signos-vitales',
    difficulty: 'medium',
    emoji: '📊',
  },
  {
    id: 'sv-7',
    front: 'FC normal en niño de 1–5 años',
    back: '80–130 lpm',
    hint: 'Los niños tienen FC más alta que los adultos',
    category: 'signos-vitales',
    difficulty: 'medium',
    emoji: '👶',
  },
  {
    id: 'sv-8',
    front: 'FR normal en lactante (0–1 año)',
    back: '30–60 respiraciones por minuto',
    hint: 'Los recién nacidos respiran mucho más rápido que los adultos',
    category: 'signos-vitales',
    difficulty: 'medium',
    emoji: '🍼',
  },
  {
    id: 'sv-9',
    front: '¿Qué es la glucemia capilar normal en ayuno?',
    back: '70–100 mg/dL',
    hint: '< 70 = hipoglucemia | > 126 = posible diabetes',
    category: 'signos-vitales',
    difficulty: 'medium',
    emoji: '🩸',
  },
  {
    id: 'sv-10',
    front: 'Presión arterial sistólica mínima aceptable en adulto con shock',
    back: '≥ 90 mmHg sistólica (meta de reanimación)',
    hint: 'En trauma craneoencefálico la meta es ≥ 110 mmHg',
    category: 'signos-vitales',
    difficulty: 'hard',
    emoji: '⚠️',
  },

  // ─── FARMACOLOGÍA (15) ─────────────────────────────────────────────────────
  {
    id: 'farm-1',
    front: 'Epinefrina (Adrenalina) — dosis y uso',
    back: 'Anafilaxia: 0.01 mg/kg IM (máx 0.5 mg) | Paro cardíaco: 1 mg IV cada 3–5 min',
    hint: 'Agonista α y β. Primera línea en anafilaxia y paro',
    category: 'farmacologia',
    difficulty: 'hard',
    emoji: '💉',
  },
  {
    id: 'farm-2',
    front: 'Aspirina (AAS) — dosis y uso',
    back: '160–325 mg VO masticada en síndrome coronario agudo (SCA)',
    hint: 'Antiagregante plaquetario. Contraindicada en alergia, sangrado activo',
    category: 'farmacologia',
    difficulty: 'easy',
    emoji: '💊',
  },
  {
    id: 'farm-3',
    front: 'Naloxona — dosis y uso',
    back: '0.4–2 mg IM/IV/IN; repetir cada 2–3 min si no hay respuesta',
    hint: 'Antagonista opioide. Titular hasta respiración adecuada',
    category: 'farmacologia',
    difficulty: 'medium',
    emoji: '🚫',
  },
  {
    id: 'farm-4',
    front: 'Atropina — dosis y uso',
    back: '0.5–1 mg IV para bradicardia sintomática; máx 3 mg total',
    hint: 'Anticolinérgico. No eficaz en BAV de 2° tipo II o 3° grado',
    category: 'farmacologia',
    difficulty: 'medium',
    emoji: '🫀',
  },
  {
    id: 'farm-5',
    front: 'Glucosa Dextrosa 50% (D50) — dosis y uso',
    back: '25 g (50 mL de D50%) IV para hipoglucemia sintomática',
    hint: 'Confirmar vía IV permeable antes de administrar',
    category: 'farmacologia',
    difficulty: 'medium',
    emoji: '🍬',
  },
  {
    id: 'farm-6',
    front: 'Nitroglicerina — dosis y uso',
    back: '0.4 mg sublingual (SL) cada 5 min × 3 dosis en dolor torácico isquémico',
    hint: 'Contraindicada: PA sistólica < 90 mmHg, uso de inhibidores PDE-5',
    category: 'farmacologia',
    difficulty: 'medium',
    emoji: '💛',
  },
  {
    id: 'farm-7',
    front: 'Adenosina — dosis y uso',
    back: '6 mg IV rápido (push) en TSV; si no convierte: 12 mg IV',
    hint: 'Administrar en vena antecubital con flush rápido. Vida media: 10 seg',
    category: 'farmacologia',
    difficulty: 'hard',
    emoji: '⚡',
  },
  {
    id: 'farm-8',
    front: 'Amiodarona — dosis y uso',
    back: 'FV/TV sin pulso: 300 mg IV bolo; 2ª dosis 150 mg IV',
    hint: 'También usada en taquiarritmias estables: 150 mg en 10 min IV',
    category: 'farmacologia',
    difficulty: 'hard',
    emoji: '🔋',
  },
  {
    id: 'farm-9',
    front: 'Oxígeno — dosis y dispositivos',
    back: 'Mascarilla simple: 5–10 L/min (40–60%) | MRC (reservorio): 10–15 L/min (90–100%)',
    hint: 'Cánula nasal: 1–6 L/min (24–44%). Saturar ≥ 94%',
    category: 'farmacologia',
    difficulty: 'easy',
    emoji: '💨',
  },
  {
    id: 'farm-10',
    front: 'Morfina — dosis y uso',
    back: '2–4 mg IV cada 5–15 min titulado en dolor severo',
    hint: 'Monitorizar respiración y PA. Antídoto: Naloxona',
    category: 'farmacologia',
    difficulty: 'medium',
    emoji: '😌',
  },
  {
    id: 'farm-11',
    front: 'Fentanilo — dosis y uso',
    back: '1–2 mcg/kg IV/IM/IN en dolor severo o sedoanalgesia',
    hint: 'Inicio: 1–2 min IV. 100× más potente que morfina',
    category: 'farmacologia',
    difficulty: 'hard',
    emoji: '🎯',
  },
  {
    id: 'farm-12',
    front: 'Midazolam — dosis y uso',
    back: '0.1 mg/kg IV/IM/IN en convulsiones o sedación (máx 5 mg)',
    hint: 'Benzodiacepina. Monitorizar vía aérea y respiración',
    category: 'farmacologia',
    difficulty: 'hard',
    emoji: '🌙',
  },
  {
    id: 'farm-13',
    front: 'Labetalol — dosis y uso',
    back: '20 mg IV lento en crisis hipertensiva; repetir 40–80 mg c/10 min',
    hint: 'Bloqueador α y β. Contraindicado en asma, bradicardia, ICC descompensada',
    category: 'farmacologia',
    difficulty: 'hard',
    emoji: '🔴',
  },
  {
    id: 'farm-14',
    front: 'Dopamina — dosis y uso',
    back: '5–20 mcg/kg/min IV en infusión para shock cardiogénico/distributivo',
    hint: 'Dosis bajas: efecto renal. Altas: vasoconstricción. Usar bomba de infusión',
    category: 'farmacologia',
    difficulty: 'hard',
    emoji: '⚙️',
  },
  {
    id: 'farm-15',
    front: 'Metoprolol — dosis y uso',
    back: '5 mg IV lento cada 5 min (máx 15 mg) en taquiarritmias',
    hint: 'Betabloqueador cardioselectivo. Contraindicado en shock, BAV, broncoespasmo',
    category: 'farmacologia',
    difficulty: 'hard',
    emoji: '🛑',
  },

  // ─── NEMOTECNIAS (10) ─────────────────────────────────────────────────────
  {
    id: 'nem-1',
    front: '¿Qué significa FAST?',
    back: 'Face (Cara) – Arms (Brazos) – Speech (Habla) – Time (Tiempo/Llamar)',
    hint: 'Herramienta de cribado prehospitalario para ACV/ictus',
    category: 'nemotecnias',
    difficulty: 'easy',
    emoji: '🧠',
  },
  {
    id: 'nem-2',
    front: '¿Qué significa SAMPLE?',
    back: 'Síntomas – Alergias – Medicamentos – Pasado médico – Última ingesta – Eventos previos',
    hint: 'Historia clínica enfocada. Usada en evaluación secundaria',
    category: 'nemotecnias',
    difficulty: 'easy',
    emoji: '📋',
  },
  {
    id: 'nem-3',
    front: '¿Qué significa OPQRST?',
    back: 'Onset (inicio) – Provocación/Paliación – Calidad – Región/Radiación – Severidad – Tiempo',
    hint: 'Evaluación del dolor. La S usa escala 0–10',
    category: 'nemotecnias',
    difficulty: 'easy',
    emoji: '🔍',
  },
  {
    id: 'nem-4',
    front: '¿Qué significa AVPU?',
    back: 'Alert (Alerta) – Voice (responde a Voz) – Pain (responde a Dolor) – Unresponsive (Sin respuesta)',
    hint: 'Evaluación rápida del nivel de consciencia. A = normal; P/U = grave',
    category: 'nemotecnias',
    difficulty: 'easy',
    emoji: '👁️',
  },
  {
    id: 'nem-5',
    front: '¿Qué significa CUPS?',
    back: 'Crítico – Urgente – Potencialmente urgente – Stable (Estable)',
    hint: 'Sistema de clasificación prehospitalaria de gravedad',
    category: 'nemotecnias',
    difficulty: 'medium',
    emoji: '🏥',
  },
  {
    id: 'nem-6',
    front: '¿Qué significa DCAP-BTLS?',
    back: 'Deformidades – Contusiones – Abrasiones – Penetraciones | Burns (quemaduras) – Tenderness (sensibilidad) – Lacerations – Swelling (edema)',
    hint: 'Lista de hallazgos en exploración física del trauma. Se usa en evaluación secundaria',
    category: 'nemotecnias',
    difficulty: 'medium',
    emoji: '🔎',
  },
  {
    id: 'nem-7',
    front: '¿Qué significa START?',
    back: 'Simple Triage And Rapid Treatment — triage masivo en 4 colores',
    hint: 'Negro (fallecido), Rojo (inmediato), Amarillo (diferido), Verde (menor)',
    category: 'nemotecnias',
    difficulty: 'medium',
    emoji: '🏷️',
  },
  {
    id: 'nem-8',
    front: '¿Qué significa AEIOU-TIPS?',
    back: 'Alcohol – Epilepsia – Insulina – Opiáceos – Uremia | Trauma – Infección – Psiquiátrico – Stroke/Shock',
    hint: 'Causas de alteración del nivel de consciencia (AMS)',
    category: 'nemotecnias',
    difficulty: 'hard',
    emoji: '💡',
  },
  {
    id: 'nem-9',
    front: '¿Qué significa TICLS?',
    back: 'Tono – Interactividad – Consolabilidad – Look/Mirada – Speech/Habla',
    hint: 'Triángulo de evaluación pediátrica (TEP). Valoración visual en < 30 seg',
    category: 'nemotecnias',
    difficulty: 'hard',
    emoji: '🧸',
  },
  {
    id: 'nem-10',
    front: '¿Qué significa PAT (Triángulo de Evaluación Pediátrica)?',
    back: 'Apariencia – Work of Breathing (esfuerzo respiratorio) – Circulation (circulación cutánea)',
    hint: 'Evaluación visual rápida sin instrumentos. Define urgencia y tipo de problema',
    category: 'nemotecnias',
    difficulty: 'medium',
    emoji: '△',
  },

  // ─── EVALUACIÓN (10) ──────────────────────────────────────────────────────
  {
    id: 'eval-1',
    front: 'Escala de Coma de Glasgow — rangos y significado',
    back: 'Rango 3–15. 15 = normal | 13–14 = leve | 9–12 = moderado | ≤ 8 = severo (intubación)',
    hint: 'Evalúa Apertura ocular (4), Respuesta verbal (5), Respuesta motora (6)',
    category: 'evaluacion',
    difficulty: 'medium',
    emoji: '📊',
  },
  {
    id: 'eval-2',
    front: 'Componentes de la Escala de Glasgow — Apertura ocular',
    back: '4 = espontánea | 3 = a voz | 2 = al dolor | 1 = ninguna',
    hint: 'Suma máxima para apertura ocular: 4 puntos',
    category: 'evaluacion',
    difficulty: 'medium',
    emoji: '👁️',
  },
  {
    id: 'eval-3',
    front: 'Componentes de la Escala de Glasgow — Respuesta motora',
    back: '6 = obedece órdenes | 5 = localiza | 4 = retira | 3 = flexión anormal | 2 = extensión | 1 = ninguna',
    hint: 'Postura de decorticación = 3 | Postura de descerebración = 2',
    category: 'evaluacion',
    difficulty: 'hard',
    emoji: '💪',
  },
  {
    id: 'eval-4',
    front: '¿Cuándo se indica intubación orotraqueal en base a Glasgow?',
    back: 'Glasgow ≤ 8 (no protege la vía aérea)',
    hint: '"Glasgow ≤ 8, intubar ya". Regla nemotécnica clásica',
    category: 'evaluacion',
    difficulty: 'medium',
    emoji: '🫁',
  },
  {
    id: 'eval-5',
    front: '¿Qué evalúa el sistema CUPS y cómo se clasifica Crítico?',
    back: 'Crítico: sin vía aérea/respiración/circulación, o inconsciente. Traslado inmediato',
    hint: 'Requiere intervención del paramédico para sobrevivir',
    category: 'evaluacion',
    difficulty: 'medium',
    emoji: '🚨',
  },
  {
    id: 'eval-6',
    front: 'Evaluación primaria — secuencia XABCDE',
    back: 'X-hemorragia exanguinante | A-vía aérea | B-ventilación | C-circulación | D-déficit neuro | E-exposición',
    hint: 'X viene del control de hemorragias masivas antes que nada (concepto TCCC)',
    category: 'evaluacion',
    difficulty: 'hard',
    emoji: '🔑',
  },
  {
    id: 'eval-7',
    front: 'Signos de shock en adulto (compensado)',
    back: 'Taquicardia, piel pálida/fría/diaforética, llenado capilar > 2 seg, ansiedad',
    hint: 'PA puede estar NORMAL en shock compensado. No confundirse',
    category: 'evaluacion',
    difficulty: 'medium',
    emoji: '😰',
  },
  {
    id: 'eval-8',
    front: '¿Qué es el llenado capilar y cuál es el valor normal?',
    back: 'Tiempo de recuperación del color cutáneo tras presión. Normal: < 2 segundos',
    hint: '> 2 seg en adulto sugiere hipoperfusión periférica',
    category: 'evaluacion',
    difficulty: 'easy',
    emoji: '🤚',
  },
  {
    id: 'eval-9',
    front: 'Triage START — criterios para color ROJO (inmediato)',
    back: 'FR > 30 rpm, o llenado capilar > 2 seg, o no obedece órdenes simples',
    hint: 'Solo uno de los 3 criterios es suficiente para clasificar como Rojo',
    category: 'evaluacion',
    difficulty: 'hard',
    emoji: '🔴',
  },
  {
    id: 'eval-10',
    front: '¿Cómo se evalúa la ventilación en la evaluación primaria?',
    back: 'Ver movimiento torácico, oír entrada de aire, sentir flujo. Simetría, uso de músculos accesorios, SpO₂',
    hint: 'Buscar: neumotórax, hemotórax, tórax en volante, quemaduras vía aérea',
    category: 'evaluacion',
    difficulty: 'medium',
    emoji: '👀',
  },

  // ─── ANATOMÍA (8) ─────────────────────────────────────────────────────────
  {
    id: 'anat-1',
    front: '¿Dónde se localiza el corazón en el tórax?',
    back: 'Mediastino medio, entre los pulmones. 2/3 a la izquierda del esternón',
    hint: 'El ápex apunta hacia el 5° espacio intercostal, línea medioclavicular izquierda',
    category: 'anatomia',
    difficulty: 'easy',
    emoji: '❤️',
  },
  {
    id: 'anat-2',
    front: '¿Cuáles son los cuatro cuadrantes abdominales?',
    back: 'Cuadrante Superior Derecho (CSD), Superior Izquierdo (CSI), Inferior Derecho (CID), Inferior Izquierdo (CII)',
    hint: 'CSD: hígado, vesícula. CII: sigmoide. CID: apéndice',
    category: 'anatomia',
    difficulty: 'easy',
    emoji: '🔲',
  },
  {
    id: 'anat-3',
    front: '¿Qué es el triángulo de Kiesselbach?',
    back: 'Zona vascular de la parte anterior del tabique nasal, origen más frecuente de epistaxis anterior',
    hint: 'Plexo venoso de Little. Tratamiento: presión directa 10–15 min',
    category: 'anatomia',
    difficulty: 'hard',
    emoji: '👃',
  },
  {
    id: 'anat-4',
    front: '¿Cuántas vértebras cervicales existen?',
    back: '7 vértebras cervicales (C1–C7). C1 = Atlas, C2 = Axis',
    hint: 'La columna vertebral total: 7C + 12T + 5L + 5S + 4Cx',
    category: 'anatomia',
    difficulty: 'easy',
    emoji: '🦴',
  },
  {
    id: 'anat-5',
    front: '¿Dónde se auscultan los ruidos respiratorios en cada pulmón?',
    back: 'Campos anteriores: debajo de las clavículas. Posteriores: entre escápulas y bases pulmonares',
    hint: 'Auscultar al menos 4 puntos: 2 anteriores y 2 posteriores/laterales',
    category: 'anatomia',
    difficulty: 'medium',
    emoji: '👂',
  },
  {
    id: 'anat-6',
    front: '¿Qué órganos son retroperitoneales?',
    back: 'Riñones, uréteres, páncreas (cuerpo/cola), aorta abdominal, VCI, duodeno (2ª–4ª porciones)',
    hint: 'Nemotecnia SADPUCKER: Suprarrenales, Aorta, Duodeno, Páncreas, Uréteres, Colon, Riñones, Esófago (recto)',
    category: 'anatomia',
    difficulty: 'hard',
    emoji: '🫀',
  },
  {
    id: 'anat-7',
    front: '¿Cuál es el hueso más largo del cuerpo?',
    back: 'El fémur (hueso del muslo)',
    hint: 'Una fractura de fémur puede causar pérdida de 1–2 L de sangre',
    category: 'anatomia',
    difficulty: 'easy',
    emoji: '🦵',
  },
  {
    id: 'anat-8',
    front: '¿Qué estructura anatómica separa la faringe de la tráquea?',
    back: 'La epiglotis — cubre la glotis durante la deglución para evitar aspiración',
    hint: 'En intubación se visualiza la epiglotis para identificar las cuerdas vocales',
    category: 'anatomia',
    difficulty: 'medium',
    emoji: '🔒',
  },

  // ─── PROTOCOLOS (7) ───────────────────────────────────────────────────────
  {
    id: 'prot-1',
    front: 'Secuencia de RCP básica en adulto (BLS)',
    back: '1. Verificar seguridad 2. Comprobar respuesta 3. Activar SEM 4. C-A-B: Compresiones (30:2), Abrir vía aérea, Ventilaciones. 5. DEA',
    hint: 'Compresiones: 100–120/min, 5–6 cm profundidad, relación 30:2',
    category: 'protocolos',
    difficulty: 'easy',
    emoji: '🫀',
  },
  {
    id: 'prot-2',
    front: 'Protocolo de manejo inicial del shock hipovolémico',
    back: '1. Vía aérea + O₂ 2. Acceso IV × 2 (calibre grueso) 3. Cristaloides calientes 4. Control de hemorragia 5. Posición Trendelenburg 6. Traslado rápido',
    hint: 'Meta: PA sistólica ≥ 90 mmHg (hipotensión permisiva en trauma penetrante)',
    category: 'protocolos',
    difficulty: 'hard',
    emoji: '🩸',
  },
  {
    id: 'prot-3',
    front: 'Pasos del protocolo de atención en anafilaxia',
    back: '1. Retirar alérgeno 2. Epinefrina 0.01 mg/kg IM muslo anterolateral 3. O₂ 4. IV + cristaloides 5. Antihistamínico + corticoide 6. Salbutamol si broncoespasmo 7. Monitoreo continuo',
    hint: 'Epinefrina es SIEMPRE la primera línea. No retrasar por antihistamínicos',
    category: 'protocolos',
    difficulty: 'hard',
    emoji: '🐝',
  },
  {
    id: 'prot-4',
    front: 'Protocolo ACLS para FV/TV sin pulso',
    back: '1. RCP 2 min 2. Desfibrilar 3. RCP 2 min + Epinefrina 1 mg IV 4. Desfibrilar 5. RCP + Amiodarona 300 mg IV 6. Repetir ciclos',
    hint: 'Desfibrilación lo antes posible. Minimizar interrupciones de compresiones',
    category: 'protocolos',
    difficulty: 'hard',
    emoji: '⚡',
  },
  {
    id: 'prot-5',
    front: 'Protocolo de inmovilización de columna cervical',
    back: '1. Estabilización manual en línea 2. Collar cervical talla correcta 3. Tabla espinal o colchón de vacío 4. Cintas de sujeción (cintura → tórax → cabeza)',
    hint: 'Mantener posición neutra. No forzar si hay resistencia o dolor',
    category: 'protocolos',
    difficulty: 'medium',
    emoji: '🦺',
  },
  {
    id: 'prot-6',
    front: 'Manejo prehospitalario del ACVA/ictus (protocolo)',
    back: '1. Identificar con FAST 2. Glucemia (descartar hipoglucemia) 3. O₂ si SpO₂ < 94% 4. IV 5. Notificar hospital código ictus 6. Traslado rápido (ventana 4.5h fibrinólisis)',
    hint: 'TIME IS BRAIN: cada minuto sin tratamiento = 1.9 millones de neuronas',
    category: 'protocolos',
    difficulty: 'hard',
    emoji: '🧠',
  },
  {
    id: 'prot-7',
    front: 'Protocolo de manejo de convulsiones activas',
    back: '1. Seguridad del paciente 2. Posición lateral de seguridad 3. O₂ 4. Glucemia 5. Midazolam 0.1 mg/kg IM/IV/IN 6. Si persiste: Diazepam 5–10 mg IV 7. Monitoreo',
    hint: 'NO introducir objetos en la boca. Proteger cabeza. Buscar causa subyacente',
    category: 'protocolos',
    difficulty: 'medium',
    emoji: '⚡',
  },
];

export const CATEGORIES_CONFIG = [
  { id: 'all', label: 'Todas', icon: '🎯', color: 'from-slate-500 to-gray-600' },
  { id: 'signos-vitales', label: 'Signos Vitales', icon: '🩺', color: 'from-red-500 to-rose-600' },
  { id: 'farmacologia', label: 'Farmacología', icon: '💊', color: 'from-emerald-500 to-green-600' },
  { id: 'nemotecnias', label: 'Nemotecnias', icon: '🧠', color: 'from-purple-500 to-violet-600' },
  { id: 'evaluacion', label: 'Evaluación', icon: '📋', color: 'from-blue-500 to-indigo-600' },
  { id: 'anatomia', label: 'Anatomía', icon: '🦴', color: 'from-amber-500 to-orange-600' },
  { id: 'protocolos', label: 'Protocolos', icon: '🚑', color: 'from-teal-500 to-cyan-600' },
];

export const STUDY_MODES = [
  {
    id: 'study',
    label: 'Estudio completo',
    description: 'Todas las cartas en orden',
    icon: '📚',
  },
  {
    id: 'review',
    label: 'Repaso rápido',
    description: 'Solo las difíciles',
    icon: '⚡',
  },
  {
    id: 'random',
    label: 'Modo aleatorio',
    description: 'Cartas en orden aleatorio',
    icon: '🎲',
  },
];
